### ISSUE TITLE
File upload API request returns status 500

### ISSUE THREAD

**Issue by bwoolnough** [eyeson-team/api#10]
I have tried to upload a file by making a post request as stated in the API documentation - https://eyeson-team.github.io/api/api-reference/#file-management.

I am unsure of what the 'file' parameter should be as the description in the documentation does not explain this. Using a local file path and a URL both return a response with status 500.

It would be useful if there was an example request in the docs and maybe some description of how this should work.

**Comment by unused** [comment]
You can simply upload a file, for sure this depends on your environment and the target platform you are developing for. Please have a look at the following example: Use `curl -XPOST -F "file=@`pwd`/image.png" https://api.eyeson.team/rooms/<access-token>/files` to upload a given file image.png in current working directory.
