### ISSUE TITLE
Missing documentation of 410 GONE for "room gone"

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/api#101]
On this page [https://eyeson-team.github.io/api/api-reference/#eyeson-room](https://eyeson-team.github.io/api/api-reference/#eyeson-room) it is documented that you can call /rooms/:access_key and you get
RESPONSES 200 OK, 404 NOT FOUND

But I just received 410 GONE. Which is nicer than 404 but not documented. I know that it happens but also it's not well documented when it happens. I guess if a meeting is shutdown? And shutdown means no remaining participants? Would be nice to have a simple meeting status flow diagram too somewhere...

**Comment by unused** [comment]
Thank you for the feedback. You are very right, this status is used when the access key has expired (the meeting has been shutdown). I'll update the documentation asap!
