### ISSUE TITLE
Cannot download the recording

### ISSUE THREAD

**Issue by romashauk** [eyeson-team/api#102]
I found an error with a few videos. For example, Recording ID is 60411cb86f2743001254d824
The problem when I am trying to download the record. It shows the following error: 

<img width="1314" alt="Screen Shot 2021-03-10 at 19 05 15" src="https://user-images.githubusercontent.com/43916092/110668950-863b1180-81d4-11eb-9115-178e8153548e.png">

Seems that something is missing from your side.
Previously, I have not come across the problem.

Any ideas on how to fix that ?

**Comment by romashauk** [comment]
Any updates ? @unused @opusonline

**Comment by unused** [comment]
Thank you for the details, we'll have a look at your issue as soon as possible. As you've also reached out to our support they will provide you any updates.

**Comment by romashauk** [comment]
@unused @opusonline Still no updates
is it a problem to fix the bug?
