### ISSUE TITLE
Receiving the webhook with the same type two times

### ISSUE THREAD

**Issue by romashauk** [eyeson-team/api#103]
Receiving the webhook with the type  "recording_update" two times, after the recording has been stopped
Check it out please @opusonline @unused

**Comment by romashauk** [comment]
<img width="1440" alt="Screen Shot 2021-03-14 at 11 10 37" src="https://user-images.githubusercontent.com/43916092/111063253-284d4900-84b6-11eb-8379-b6bd0e68d01f.png">
**Logs**

**Comment by romashauk** [comment]
@unused @opusonline Any updates on the bug ?

**Comment by unused** [comment]
Thank you for the feedback, this is a result of how we trigger the webhooks but does not change the resulting details. We'll revisit and discuss the trigger internally and try to reduce those transports. Best wishes!

**Comment by romashauk** [comment]
@unused Could you please explain what does it mean? 
The problem appears last Friday, before Friday it works properly

The Webhook with the same event triggers two rimes. 
Why it works like that and how to avoid that? 
It is not a proper behaviour of webhooks

**Comment by unused** [comment]
Thanks again - we will release a patch if we find the request doubled for no reason. However you should not expect webhooks to be delivered unique, there are several reasons details can be transported multiple times. Best wishes!
