### ISSUE TITLE
api.eyeson.team page not found

### ISSUE THREAD

**Issue by choksifenil90** [eyeson-team/api#104]
It shows the error.

This api.eyeson.team page can’t be found. 
No webpage was found for the web address: https://api.eyeson.team/
HTTP ERROR 404

please have a look at below screenshot

![Screenshot (312)](https://user-images.githubusercontent.com/47699029/111141630-c66e0b80-85a9-11eb-97e0-de4c030fad35.png)

**Comment by unused** [comment]
Please find details on how to interact with the API in the [API documentation](https://eyeson-team.github.io/api/api-reference/). Best wishes!
