### ISSUE TITLE
Using very long playbacks

### ISSUE THREAD

**Issue by medelmourabite** [eyeson-team/api#105]
Is it possible to add playbacks of more than 30min?
I tested some videos and it works except that some videos will stop at 30s, 2min and somes in 15min

**Comment by unused** [comment]
Thanks for the valuable feedback, I do not know of certain limits but I'm happy to test for any. If known, can you provide us some details on the video files used like format, video & audio codec, dimension, frame rate, etc. so we can add some of similar format to our testsuites?

**Comment by medelmourabite** [comment]
Thanks for your replay, can you provide a format that works? and we will use it instead
Our only need is to play longer playbacks of 30-60min
I used mp4 videos of different durations but mostly for testing
Format: mp4
Dimensions: 1280x720, 1920x1080
Codecs: AAC, H.264
frame rate: 30

**Comment by unused** [comment]
Thank you for the details, the format looks good. We will include longer video files in our tests and optimize the media inject service if we find any troubles.

**Comment by unused** [comment]
We had several test-runs with long video files with up to one hour but did not see any troubles. However it might be possible that certain storage provider cause some issues. If you can it would be nice if you share which provider you used to host the data for your tests, so we can test this provider as well.
