### ISSUE TITLE
meeting recording error

### ISSUE THREAD

**Issue by Costablancaevents** [eyeson-team/api#107]
I'm looking at meeting recordings, at the one on 04/07, 11:54 AM produces the following error ;

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Resource>
/meetings/5f0051c3841afa174f0d581d/5f00539f17b6f23ff03d3495?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AH07FBAZO9IYS38J6742%2F20210330%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210330T073953Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=6328677f4c2e5aed41ed532348c6bb210109825311f7adebf79c2d32d02097d0
</Resource>
<RequestId>1617089994048517</RequestId>
</Error>

How can I access it ?

**Comment by unused** [comment]
Thank you for reaching out - this seems rather an issue for our support team and I'd kindly ask you to [contact them instead](https://help.eyeson.com/kb-tickets/new). Best wishes!
