### ISSUE TITLE
Stop recording 404  

### ISSUE THREAD

**Issue by florentcadot** [eyeson-team/api#108]
Hi !
We use your API ( https://eyeson-team.github.io/api/api-reference/#recording) to start recording in a meeting:
````POST /rooms/:access_key/recording```` everything works fine

![3](https://user-images.githubusercontent.com/52289507/113933497-f600e400-97f4-11eb-8104-c64335edc6c8.jpg)

But when we try to stop recording using ````DELETE /rooms/:access_key/recording````
we have a 404 Error (we use the same "access_key" as URL parameter and we were sure the recording had already started )

![2](https://user-images.githubusercontent.com/52289507/113933612-15980c80-97f5-11eb-92fa-70de70fd5035.jpg)

It works fine from eyeson embed iframe player.

**Comment by unused** [comment]
Please ensure the tool you are using is configured properly and you do not try to stop a non-existing recording (e.g. already stopped). If double checked the correct HTTP status codes are received using the following snippet:

```sh
export ACCESS_KEY=...
curl -v -X POST "https://api.eyeson.team/rooms/$ACCESS_KEY/recording" #  HTTP/2 201
curl -v -X DELETE "https://api.eyeson.team/rooms/$ACCESS_KEY/recording" # HTTP/2 200
```

Did you set the Authentication Header with API Key? This would be wrong and results in trying to delete a recording rather to stop it. Remember that the access key is an authentication method for participants, the API key however is not meant to be used on a client leven!

**Comment by florentcadot** [comment]
Hi @unused !

"Did you set the Authentication Header with API Key?" Yes ! It works perfectly fine with only the access key

Thank you very much for your help !

Regards
