### ISSUE TITLE
Get current video conference users id's

### ISSUE THREAD

**Issue by VangelIliev** [eyeson-team/api#109]
Hi I am a developer from SI Digital Solutions I wanted to know do you have functionality to get all joined users id's in existing video room ? thank you

**Comment by unused** [comment]
Depending on your requirements there are several methods to do so. The most basic one is to store or fetch the id's server side when [joining your participants](https://eyeson-team.github.io/api/api-reference/#eyeson-room). You can also keep track of who joined a meeting [using webhooks](https://eyeson-team.github.io/api/api-reference/#register-webhooks). If you need this information on client-side you can check the events for [joining and leaving users](https://eyeson-team.github.io/js-docs/events/#joining-and-leaving-users). Do not hesitate to leave a comment if you have any further questions on this.
