### ISSUE TITLE
Broken links in 'Broadcast' documentation

### ISSUE THREAD

**Issue by bwoolnough** [eyeson-team/api#11]
I would like to test YouTube streaming, however I do not know what the stream_url parameter for the post request should be.

The links to the instructions for receiving a streaming URL do not work (https://eyeson-team.github.io/api/api-reference/#broadcast).

**Comment by unused** [comment]
Thanks for the heads up - corresponding links are https://developers.facebook.com/docs/live-video-api and https://developers.google.com/youtube/v3/live/getting-started
