### ISSUE TITLE
iOS problem with streaming video

### ISSUE THREAD

**Issue by Icaka99** [eyeson-team/api#110]
Hi guys, I am Web Developer at SI Digital Solutions. We integrated your API in our WebSite using WebRtc. Everything works fine with desktop and android. When we start the video streaming on iOS, the video freezes. Other participants can hear and see the one with iOS, but he can NOT see and hear anything, the video stays frozen. We tried with Iphone XR and Iphone 11 Pro. It's the same issue. I wanted to ask if you guys know what causes the problem and if it's caused by us or by you. And if it's working generally so we can search the problem in us. If you have any advices how to solve the problem would be great! Thanks and keep up the good work!

**Comment by opusonline** [comment]
Hello, thank you for your feedback!
iOS can be really tricky. Here are some tips that might help.
- you can split the remote stream's audio and video to play audio in a separate audio element
- for the video element it is required to have the attributes `playsInline` and `autoplay` in place

Here's a more detailed article about Safari issues: https://techblog.eyeson.team/post/safari-sfu/
Hope this helps!
Do not hesitate to leave a comment if you have any further questions on this.

**Comment by Icaka99** [comment]
Thank you very much, these attributes "playsInline" and "autoplay" worked for me!
