### ISSUE TITLE
GET /rooms/:access_key/users  fetch current users in a room

### ISSUE THREAD

**Issue by guymoller** [eyeson-team/api#111]
I was wondering how can I fetch a list of the current users in a room. I would like to use it in order to manipulate the layout programmatically.
Your API has the endpoint `GET /rooms/:access_key/users/:identifier` but not  `GET /rooms/:access_key/users/`

what is the best practice to achieve this list? can I also fetch the list of guests?

**Comment by unused** [comment]
We do not provide this information via REST endpoints as it changes often.

A common case is that our customers setup an additional control user interface.  You can easily do this using the [eyeson JavaScript package](https://eyeson-team.github.io/js-docs/). As you connect to the meeting (e.g. an extra user named layout manager w/o streaming), you will receive a participants list, as well as events as they leave or new participants join. Let me know if you need any further details on this.

A small number of our customers require the participants on server side which we deliver as a strict premium feature. Please contact our sales team (sales@eyeson.com) in case it is a must-have for your application.
