### ISSUE TITLE
Speaker label with names

### ISSUE THREAD

**Issue by Icaka99** [eyeson-team/api#113]
Hello guys! We have implemented your API in our website and we are having a trouble with showing label with names when someone is speaking. I was wondering if it works out of the box, because I saw there is the desired label implemented from you when someone turns off his camera(with an API request). I was wondering if there is a request or anything that can show/hide that label whenever we want - with a button or something. It will be very helpful if you can give an example for the request eventually. We are using .Net Framework/JS in our website. Greetings from Bulgaria and thank you in advance!

**Comment by unused** [comment]
Hi there, nice to meet you! Just to go sure that I got you right: you deactivate the display of names in the video using `options[show_names]=false` for you meetings and want to display voice activity by yourself in a custom web user interface. Am I right?

**Comment by Icaka99** [comment]
No, I have that parameter(show_names) to default - which is "true". The label I am talkin about is that in the picture, but it is only visible, when I set the video parameter to "false". I want the label to be visible always or if I could turn it on/off.
![image](https://user-images.githubusercontent.com/60925985/138273337-34fedde3-5e24-444b-ba54-b886dd66c818.png)

**Comment by unused** [comment]
We do show a microphone icon at the name insert when we detect a voice activation. This is automatically done when `show_names` is active. As you figured out correctly, as participants are not part of the video podium, there voice activity is shown in an extra label. This label cannot be deactivated.

![Screenshot from 2021-10-21 14-28-19](https://user-images.githubusercontent.com/59397/138277208-19e28de9-6889-4f29-b801-74f22a239cf9.png)

Do you specifically need to turn it off? Would you mind sharing details of your use case than?

**Comment by Icaka99** [comment]
I don't want to turn it off. I want to turn it ON even if the participants are part of the video podium.

**Comment by unused** [comment]
Thank you for the clarification, I discussed this with a core team and we'll think about a solution for your requirement. Currently we do handle voice activation for active video participants showing the microphone at the name only and for audio only participants we show the label. I'll add a comment when I have any updates on this topic.

**Comment by unused** [comment]
A recent update [has introduced new configuration parameters](https://eyeson-team.github.io/api/api-reference/#layout) to handle the audio insert independently.
