### ISSUE TITLE
Full screen not working

### ISSUE THREAD

**Issue by rohithcirakas** [eyeson-team/api#114]
Hi we are trying to integrate Eyes on in our web-app by showing the GUI in an iframe. When we click on 'Full screen' we are getting the following error 'There was an error while switching to Full screen, try again if something doesn't seem to work'. Can we disable this button in GUI via API options. 
How can we resolve this issue?

![sc2](https://user-images.githubusercontent.com/70321228/141077967-be08c27b-8b4f-45c9-b34a-044ca8e1b23c.png)

**Comment by unused** [comment]
Did you set the [feature policy in the allow atttribute](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy/Using_Feature_Policy#the_iframe_allow_attribute) properly?

**Comment by rohithcirakas** [comment]
Thank you for your response. We will try and update you soon.
