### ISSUE TITLE
Webhooks - Integrity checking failure for the 'recording_update' event.

### ISSUE THREAD

**Issue by rohithcirakas** [eyeson-team/api#115]
Dear Team,

We are using Eyeson in one of our web-application for live video conferencing. Referring the documentation, we register webhooks for "room_update" and "recording_update" types to get the updates.
Now, we are facing a problem with integrity checking, with computed SHA256 HMAC and given x-eyeson-signature value in request header in case of "recording_update" event type.

The same integrity checking can be successfully done with "room_update" event type. The sample request is given below for the reference.

### Request Body ###
 ` {"timestamp":1637057119,"type":"room_update","room":{"id":"meetingxxxxxxxxx_1","name":"room1","ready":true,"started_at":"2021-11-16T10:05:16.667Z","shutdown":false,"sip":{"uri":"conf_6193825c3xxxxxxxxebcc442@integrations.visocon.com","domain":"integrations.visocon.com","authorizationUser":"conf_6193825c3xxxxxxxxebcc442"}}}`
### Computed Signature : ### 
`4476a916fa34f93681b5a3e54b1c155d141c0d5bddf60c0a4f6108607fb344f5`
### x-eyeson-signature : ###
`4476a916fa34f93681b5a3e54b1c155d141c0d5bddf60c0a4f6108607fb344f5`

### Request Body ###
` {"id":"619382b5xxxxxxxxxe8bae88","created_at":1637057206,"duration":10,"links":{"self":"https://api.eyeson.team/recordings/619382b5xxxxxxxxxe8bae88","download":"https://s3.eyeson.com/meetings/xxxxxxxxxxxxxx/xxxxxxxxxxxxxxxx"},"user":{"id":"6193825cxxxxxxxxxxbcc443","name":"Arxxxxxxxxxxxxxx","avatar":null,"guest":false,"joined_at":"2021-11-16T10:05:19.278Z"},"room":{"id":"meetingxxxxxxxxx_1","name":"room1","ready":true,"started_at":"2021-11-16T10:05:16.667Z","shutdown":false,"sip":{"uri":"conf_6193825c3xxxxxxxxebcc442@integrations.visocon.com","domain":"integrations.visocon.com","authorizationUser":"conf_6193825c3xxxxxxxxebcc442"}}}}`
 ### Computed Signature : ### 
 `919ad8a54c3fa564ab5bb8106784336ceaa280c80803d046cc88992891c298f6`
 ### x-eyeson-signature : ### 
 `87f2f48883ac341e2d990250e64bfc1facee22a410ecb3e14aea872450703dca`

What might be the reason for the mismatch in case of 'recording_update' event. Could you please look into it and help us?

Thank you
Cirakas Team

**Comment by unused** [comment]
Hi there, thank you for the very detailed description. We will look into this issue asap and let you know when a fix has been released! Best wishes, Christoph

**Comment by unused** [comment]
We have double checked the signature verification but could not detect any problems there. Please ensure the message body to check is raw, as it contains a URL that must not be escaped or changed by other means. If you provide us some description of your implementation maybe we can help to solve the issue somehow.
