### ISSUE TITLE
Unable to get recorded video 

### ISSUE THREAD

**Issue by talha-hameed** [eyeson-team/api#117]
i am using eyeson trial version and I am facing an issue related to get recordings. 

step 1: start meeting and get access token https://api.eyeson.team/rooms/
step 2: https://api.eyeson.team/rooms/access-key/recording
step 3: https://api.eyeson.team/rooms/access-key/recording
step 4: https://api.eyeson.team/recordings/access-key

i am able to see the recording count increasing in dashboard.
https://accounts.eyeson.team/developer/

but i can't open that recording's videos and unable to see any records in 
 https://accounts.eyeson.team.

Anyone please can help me how can i get the recorded meeting video because when i hit this api  https://api.eyeson.team/recordings

it always return me 404 code.

In previous issue when i asked the same question i was told that recorded meeting is not available immediately. but now i have tried it even after 12 hours after meeting recorded but can't able to manage it.

**Comment by unused** [comment]
As mentioned in #116 you need to setup a webhook. Therefor you have to provide an endpoint (in your application server or another service) that is public available and [register the webhook](https://eyeson-team.github.io/api/api-reference/#register-webhooks). That's all you need to receive any recording information.

If you need any further help please let me know what development environment (programming language, containers) you are using so we can provide you with an example.

**Comment by talha-hameed** [comment]
Yeah it would be better if you can help me with an example. I am developing a mobile application in react-native in which i am using the  eyeson recording apis as mentioned above i just need to test/verify my recording that i am doing this in right way.

**Comment by unused** [comment]
That's great to read. What technology do you use on the server side that will start the meeting for your users. If you planned to start the meeting on the mobile device directly you might have missed that you cannot handle the API key as a proper secret and additionally have no control on the usage so cannot stop anyone to start video conferences even if you already exceeded your planned limits.

**Comment by talha-hameed** [comment]
i understand all these things and have manage these things and starting/stopping the meeting. I just want to know how can i register the web hook when i stop the recording from my mobile side?

**Comment by unused** [comment]
You will need a public available HTTP endpoint to register webhooks. This endpoint will receive a HTTP request as soon as a recording is started and when it is available for download. Please follow the description [from the API documentation](https://eyeson-team.github.io/api/api-reference/#register-webhooks) to set this up. Please note that you only need one endpoint and register it only a single time.
In case you get stuck on the way we are happy to help so do not hesitate to leave another comment with a detailed description of your problem.

I've re-read your messages and noticed that you wrote:
> but i can't open that recording's videos and unable to see any records in https://accounts.eyeson.team.

Unfortunately there is a misunderstanding here. The meetings found at https://accounts.eyeson.team are not associated with the ones you start using your very own custom API key. Please find further details about [the difference between eyeson and the eyeson API in our help center](https://help.eyeson.com/what-is-the-difference-between-eyeson-and-eyeson-api).
