### ISSUE TITLE
recordings api

### ISSUE THREAD

**Issue by Daesons** [eyeson-team/api#119]
Hello,

I'm looking into recording API and it looks like POST '/recording' route returns empty response, so there is no way to get id of the recording or any other information that's described in your docs here https://eyeson-team.github.io/api/api-reference/#recording.

I'm worried about how I can then get my recording entry by ID(identifier) if I don't get it on creation.
If this record identifier needs to be obtained elsewhere, please provide where they can be obtained from.

**Comment by unused** [comment]
Hi there, thank you for your feedback. In order to receive recordings you [have to register a webhook](https://eyeson-team.github.io/api/api-reference/#register-webhooks) - a single one to receive any recordings. As the recording is started by a participant, it should not be handled client-side. Additionally there is some post-processing so it will not be available immediately but a short time after it has been stopped.

Do not hesitate to leave a comment if you have any further questions on this!

**Comment by KurnosovNikita** [comment]
Hi @unused,

The same problem with the webhook API, the response is empty and doesn't work for me, no incoming requests come to my server.
Can you please tell me what I'm doing wrong or why it doesn't work?

Here is what I do:
```
var data = JSON.stringify({"url":"http://my-server/api/webhooks/room-update","types":"room_update"});

var config = {
  method: 'post',
  url: 'https://api.eyeson.team/webhooks',
  headers: { 
    'Authorization': accessKey, 
    'Content-Type': 'application/json'
  },
  data : data
};
axios(config)
...
```

Thank you in advance!

**Comment by unused** [comment]
Hello there! Please ensure your endpoint is using HTTPS. For the registration part content-type is not JSON encoded, the following will work for you:

```js
const axios = require('axios');

const data = { url: 'https://my-server/api/webhooks/room-update', types: 'room_update' };
const config = {
  method: 'post',
  url: 'https://api.eyeson.team/webhooks',
  data: data,
  headers: {
    'Authorization': process.env.API_KEY
  }
};
axios(config);
```

Do not hesitate to leave a comment if you have any further questions!

**Comment by KurnosovNikita** [comment]
Hi @unused! 

Thank you for your quick reply! That works!
Also сan you please tell me how long the webhook lives, do I need to update it after some time?

UPD: Also there is no "id" field in the response.

**Comment by unused** [comment]
The webhook is registered with your API key and will not expire or be removed. You can get information on your registered webhook using `GET /webhooks`, thank you for the feedback, we'll consider to add some `id` to the register response as well.
