### ISSUE TITLE
Screen capture post request results in grey screen

### ISSUE THREAD

**Issue by bwoolnough** [eyeson-team/api#12]
Screen capture works fine when I use the GUI but not via the API.

I have tried making post and put requests as stated in the docs - https://eyeson-team.github.io/api/api-reference/#screen-capture. The responses I get have status 201 and 200 respectively.

When I make a post request the dialog for choosing a screen does not appear and the video (where the screen capture should be) becomes grey.

I have the same issue in Chrome (with the eyeson browser extension installed) and Firefox.

**Comment by unused** [comment]
The endpoint prepares the meeting to better handle a screencapture session (e.g. updates layout configuration), however if you built a custom user interface you have to provide a stream yourself. For a web based application the eyeson JavaScript package should provide you with required utilities, you can also have a look on [this blog post about "How to build a screen sharing extension"](https://techblog.eyeson.team/post/screen-sharing/) to get some insights on this topic.

**Comment by bwoolnough** [comment]
Thanks for the reply. Hoping you can clarify a few things:

I am building an application with the eyeson GUI in an iframe and a custom interface which makes API requests via JavaScript. I want to be able to start a screen capture using the API. Is this where I would need to provide a stream myself, and if so, how would I do so?

There doesn't seem to be anything in the JavaScript package docs about starting a screen capture. How would I go about doing that with the JS package?

What is the difference between the POST and PUT requests for screen capture? Are they both required, or just different ways to achieve the same thing?

**Comment by unused** [comment]
You can trigger a screen capture handling provided by the eyeson JavaScript package or simply [provide and set the stream](https://eyeson-team.github.io/js-docs/events/#stream-update) yourself.

```
// Set audio to the current mute-state of the audio in order to reset it properly.
eyeson.send({ type: 'start_screen_capture', audio: true });
// When the screen capture session has ended, we recommend to restart the current stream.
eyeson.send({ type: 'restart_stream', options: { audio: true, video: true }});
```

Please note however that screen capturing depends heavily on how you retrieve and how you can provide the stream for eyeson in your custom application.

POST/PUT are [HTTP methods](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods) used for creating and updating resources.
