### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by FredFu0234** [eyeson-team/api#120]
Hi!

I receive HTTP 500 when I try to create room:

curl -v -X POST -d "user=MyRoom" -H "Authorization: XXXXXXX" "https://api.eyeson.team/rooms"

Response is HTTP 500 without a body.

**Comment by unused** [comment]
Hi there! The minimal argument required to join and start a meeting is a **user name**, if you additionally provide an identifier for the meeting room, all users will end up in the same meeting.

```
$ curl -X POST \
  -H "Authorization: XXXXXXX" \
  -d "id=MyRoom" \
  -d "user[name]=Alice" \
  "https://api.eyeson.team/rooms"
```

You can find more details and examples in the [API documentation](https://eyeson-team.github.io/api/getting-started/). Please do not hesitate to leave a comment if you have any further questions!
