### ISSUE TITLE
Api call to list all participants of a room

### ISSUE THREAD

**Issue by FredFu0234** [eyeson-team/api#121]
Is there a way to list all participants of a room?
I would expect somthing like 
GET /rooms/:access_key/users

**Comment by unused** [comment]
The list of participants will constantly change, therefor it is broadcasted within the websocket connection but there is no REST endpoint. If you are using the [JavaScript package](https://eyeson-team.github.io/js-docs/events/#joining-and-leaving-users) to build a custom web client, the participants will be provided as event. Let me know if you have any further questions on this!
