### ISSUE TITLE
Retrieve Websocket User Join/Leave Events

### ISSUE THREAD

**Issue by FredFu0234** [eyeson-team/api#123]
Hi!

I would like to receive Websocket events when a user joins or leaves a room.
I connect to the websocket provided in the /rooms API response and I send

{
  "command": "subscribe",
  "identifier": "{\"channel\":\"RoomChannel\"}"
}
and
{
    "command": "subscribe",
    "identifier": "{\"channel\":\"UserChannel\"}"
}

But I receive only "confirm_subscription", "room_setup", "room_ready" and "options_update" events.

How do I receive updates when a user joins or leavs?

**Comment by unused** [comment]
Hi there, I'm sorry it seems I've mixed thinks up. In current version we do not provide this information via websockets yet. There will be an update for the API service to do so, however it is not clear when it will be released yet. For now the participant join/leave details are transferred within a WebRTC datachannel for an active connection. Can you provide any details of your techn. environment so I can come up with an example for you? Thank you in advance!

**Comment by FredFu0234** [comment]
I would like to implement a portal to create rooms, schedule rooms and have a dashboard displaying all open rooms and all current participants in the rooms. As gui I use your standard gui.
The backend is written in java. So, I use javax.websocket to connect to the socket provided in the /rooms api call.
The only thing that is missing is to be informed in the java backend if a guest user joines or a user leaves the room.

**Comment by unused** [comment]
In current version we do not provide such details. In order to receive live updates you have to connect to an active meeting which also requires receiving and providing media streams. That would be an overhead to such application. We recommend to keep track for joining participants and provide this information rather than showing a live view that might be very noisy on many meetings anyway.
