### ISSUE TITLE
Muting/Kicking

### ISSUE THREAD

**Issue by natschz** [eyeson-team/api#128]
Just want to make sure, you do not support muting/kicking on the server side?

Meaning it has to be implemented client sided and there is no 100% guarantee to enforce it.

Just to be sure.

**Comment by unused** [comment]
With the current state of our service we do not provide role management. There is no "viewers only" mode to participants, but we recommend to use [broadcasting](https://eyeson-team.github.io/api/api-reference/#broadcast) that covers most of such scenarios.

We do provide some sort of user kick, however this requires additional work in your client and it allows re-join, except if a meetings participants are frozen (locked meeting). Those methods are undocumented as they depend on if a guest-join is actively used. You can checkout the default web ui client on how meeting lock and participants kick behave.
