### ISSUE TITLE
How to ensure valid guest tokens.

### ISSUE THREAD

**Issue by natschz** [eyeson-team/api#129]
Hey guys, just wanted to check back with you because I was told we don't need to "create" rooms.

1. Currently, we are fetching "create" a room by sending a POST request to  https://api.eyeson.team/rooms.
2. After this we are checking if the room is running by fetching the room information via a GET request to https://api.eyeson.team/rooms/ROOM_ID. (This is done because step one might happend a long time ago and in that case we need to create a new rom like in step 1. since the room might then be deleted. Is this correct?)
3. If the meeting is not running start over.
4. Get the guest token to create the guest access token

**Comment by unused** [comment]
There is no need to check if a meeting is running. As you provide your participating users detail - at least the name - with the `POST /room` request. A meeting will be created or the user will join an active meeting. Therefor **only** interact with the eyeson service at the moment your user actively wants to start any video communication. We ensure a meeting is ready in seconds, use the websocket connection to receive the state update or simply poll the details.

Use the room identifier `id` parameter to join different user to the same meeting. Please note that the guest-token is solely needed to create users for an active meeting in a client-to-server communication, never in server-to-server.

Let me know if you need any further details on this!

**Comment by natschz** [comment]
Yea I understand that, but let's say I'm creating a room (POST /rooms # create room a new room or join an existing by id.).
How long will this room be available?
It is possible we create this room, then days later or so, someone tries to join it. Is the (room) access_key valid forever?
Currently we are checking if the room is ready and not shutdown, so we can ensure that it is running, so people can join it.
If this is not the case we create a new room.

**Comment by unused** [comment]
The key is not to mind the life span of the temporary(!) access at all but instead handle the users in your software (are they authenticated, authorized to join the meeting), then interact with eyeson to let it handle the media, video stuff. So if a user wants to join a meeting now, then days later, both times he/she should end up somewhere in your application where you interact with eyeson and, simple forward them to the default web ui or connect them using a custom client. Never create a meeting without a participant actually joining it.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ok, but does this mean we can't reuse a room? We would like to create a room (f.e. Aula 1) and keep it accessible until  we close it manually?

**Comment by unused** [comment]
Sure, just [use a unique identifier](https://eyeson-team.github.io/api/api-reference/#eyeson-room) `id` and joining participants will always end up in the same meeting.

**Comment by h0jeZvgoxFepBQ2C** [comment]
And is the room access key still valid if the room gets automatically recreated (f.e. if a room gets closed automatically, but later gets recreated because a new user joins in)? Or do we have to fetch the room access_token again, after the room gets recreated?

**Comment by unused** [comment]
With joining a meeting you will be provided with a meeting access key, don't mind if it is the same you received beforehand or if it is a new one. The important thing is that your users interact with your software and you interact with the eyeson service only when they are ready to participate. Please don't mind to ask again if it is still unclear!

**Comment by h0jeZvgoxFepBQ2C** [comment]
What do you mean we should not mind? 
Either we have to implement a token change mechanism (save the access token, which we get back from a user joining a meeting), or the access token is valid in the long term and we don't have to implement such a mechanism?

**Comment by unused** [comment]
There is no need to store the access key, it is only a temporary authentication method that ensures the users present has been authorized by you to access a meeting. Your user wants to join a meeting **now**, at this point you "register" the user at eyeson. The access key is a shared secret that will identify this user at eyeson, therefor you only hand this access-key to your user. No further action from your side is needed.

This way you can build anything in your system independent from eyeson. Plan or schedule meetings, send invitations, manage roles, handle meeting access, etc. Only at the point your user is going to use the video/audio you interact with the eyeson service.

> We would like to create a room (f.e. Aula 1) and keep it accessible until we close it manually

I've setup [a minimalistic example](https://gist.github.com/unused/7f2a4f5d68c47c15c4d3c11940be0c2f) of your description (in go as I don't know about your environment setup). For sure you can also use a custom web, mobile or desktop client, however you still will only need to provide the access-key to this client.

**Comment by h0jeZvgoxFepBQ2C** [comment]
But how can we query then the meeting information for a room? As your API documenation says, the room information can only be queried by the access token?

![Bildschirmfoto 2022-05-03 um 13 24 11](https://user-images.githubusercontent.com/10075/166444604-b39f0514-f3b8-4598-b43b-06fdc0d7dd8e.png)

**Comment by unused** [comment]
Use [webhooks](https://eyeson-team.github.io/api/api-reference/#register-webhooks) to receive details about start, stop, recordings, snapshots.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would it be possible that EyesOn offers an API endpoint, which returns the information by providing the room id(identifier)?

**Comment by unused** [comment]
We will consider such endpoints in future versions of our services, the current state does deliver such details via webhooks.

**Comment by h0jeZvgoxFepBQ2C** [comment]
The problem with webhooks for us is, that we have multiple servers with different domains and each of these servers can "host" different rooms, so I'm not sure how we can register multiple webhooks for different rooms on different servers/domains?

**Comment by unused** [comment]
You only need **one** webhook registered. You can easily dispatch information from a single webhook receiver. Some use distinct prefixes for the room identifiers `id` to route their data.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ok, so we have to dispatch the webhooks by ourselfes with a new service?

**Comment by unused** [comment]
Yes, or one of your existing services :)
