### ISSUE TITLE
Screen Share

### ISSUE THREAD

**Issue by ashrafJebril** [eyeson-team/api#13]
i am trying to make share screen but it work localy , when i share with a a guest my screen dosent appear 

this is my function 
  function startScreenStreamFrom(streamId) {
      navigator.mediaDevices
        .getUserMedia({
          audio: false,
          video: {
            mandatory: {
              chromeMediaSource:   'desktop',
              chromeMediaSourceId: streamId,
              maxWidth:            1920,
              maxHeight:           1040,
              maxFrameRate:        15
            }
          }
      
        })

        .then(stream => {
          const videoElement = document.getElementById('video');
          videoElement.srcObject = stream;
          console.log("stram",stream)
        })
        .catch(console.error);
    }
is there any API or ID from EyesOn i have to pass it to my function ?

**Comment by unused** [comment]
How you use and provide screen capturing depends on your application, for web application you can use the [eyeson js package and update a stream accordingly](https://eyeson-team.github.io/js-docs/events/#stream-update). If you stick with the eyeson default web GUI it provides screen capturing out of the box.
