### ISSUE TITLE
Misleading layout api documentation

### ISSUE THREAD

**Issue by natschz** [eyeson-team/api#130]
I was looking at the layout API documentation (https://eyeson-team.github.io/api/api-reference/#layout), looking at the parameters list, it says "Current layouts are: present-lower-3, present-upper-6, present-upper-right-9, and present-two-upper-6." for the name parameter.

This values are kind of unclear, and missing some further description, also this list is completely missing the one, two, four and nine options, which are just briefly mentioned above.

**Comment by unused** [comment]
Thanks for the heads-up, we'll update the documentation asap.

**Comment by natschz** [comment]
Thanks!
