### ISSUE TITLE
Unexpected behavior with layouts

### ISSUE THREAD

**Issue by natschz** [eyeson-team/api#131]
According to the [documentation](https://eyeson-team.github.io/api/api-reference/#layout), the **users** parameter is optional.

But if the users parameter is omitted, setting the layout to e.g. "one" doesn't have any effect. After setting the users to an array of two empty strings, then all layouts (including the bigger ones like "nine") work.

This is quite unexpected behavior.

In addition to that, when not setting the layout, so that it should be the automatic layout, will not work if the users parameter is set to an array of two empty strings, this will cause the layout to be just two side by side.

**Comment by unused** [comment]
Thank you for your feedback, we'll test the described layout configurations and reply with some details.

**Comment by btreuer** [comment]
Thank you for your question. You are right. Not setting a user array sets the layout always to auto. A user array is needed to set a custom layout.
Therefore, if you have an user array with two users, the MCU-mode is active and the layout is set to "two" empty spots (splitting the podium).
Additional information on layouts: https://techblog.eyeson.team/posts/podium-layouts/
