### ISSUE TITLE
Can an existing user be renamed?

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/api#133]
Can an existing user be renamed after POST request and how?
I did not find it in the docs here: [https://eyeson-team.github.io/api/api-reference/#user-and-guest-user](https://eyeson-team.github.io/api/api-reference/#user-and-guest-user)

If not what is the advised workflow? New user?

**Comment by unused** [comment]
If you need to rename a user disconnect the active participant, provide a name form and create a new user. On connecting new participants to the meeting for every other client the list of participants will show the correct information.

We did not find a use-case that would require a direct update of name but are interested to see some.

**Comment by codingyourlife** [comment]
use case:
how about everyone joining with anonymous user getting a random name and noone knows who is who? you want to change it to your own name then. during the call

**Comment by unused** [comment]
For sure we have discussed such plain scenarios but came up with many arguments against: If you provide a direct update, the participants list will get unclear as people can constantly choose different names w/o others getting noticed. If you decide to show a note as well, it can get very noisy. In case people join with random names and this is a problem, it's better to not provide this option at all. Using your platform to join users guarantees that their authenticated name will be shown. If there is no way around, having a short reconnect doesn't seem bad as other participants will recognize the change.
