### ISSUE TITLE
View ribbon, Stop incoming video, Multiple streams

### ISSUE THREAD

**Issue by dispbd** [eyeson-team/api#134]
Hello. There are several questions regarding the API of your service.

### 1. View ribbon.
![View ribbon](https://user-images.githubusercontent.com/45291423/185664772-b5812bc0-358d-4ae0-9454-cdfe106b8112.png)
I did not find a way to make a similar layout (as on the left or right in the picture). Or am I just not understanding?
Is it possible? Is it possible to create custom view via layout request (_**POST /rooms/:access_key/layout**_)?

### 2. Stop incoming video.
I know that you can turn off the video stream for participants. But is it possible to mute the incoming video for a participant and leave only the audio?
About the same as [Zoom.](https://support.zoom.us/hc/en-us/articles/4409500570381-Stopping-all-incoming-video-in-a-meeting-or-webinar)
If so, can you show how to implement it? I tried to do it through the audio tag, but it didn't work. If this is not possible, is such a feature planned?

### 3. Multiple streams.
As I understand it, eyeson returns only one remote stream. This gives an advantage in performance and video quality. But this is also a minus - it is more difficult to control the layout of the conference.
![internal user IDs](https://i.vgy.me/en6xVy.png)
As I understand it, there are internal user IDs. Is it possible to get the video stream of an individual user? Or get an array of streams of all participants at once? For example, alternative services use the **_SharedArrayBuffer_** approach. Perhaps there are other approaches (I'm not very strong in this).
This would solve the problem stated in the first question, since the user is in control of the layout. Moreover, it would allow making such convenient functions as binding buttons to a separate participant flow, etc.
Is it possible to implement this? Or maybe you know some alternative solutions?
If not, is such a feature planned?

**Comment by unused** [comment]
Thank you for the feedback and detailed description. The eyeson service is build around it's [single stream technology](https://help.eyeson.com/what-is-single-stream-technology), we do provide an [SFU mode](https://blog.eyeson.com/mcu-sfu-mode) only if there are two participants, while still handling recording or snapshots on demand.

Video podium layouts are currently limited to the [preconfigured ones](https://eyeson-team.github.io/api/api-reference/#layout) yet we are very flexible on this and will add some for you if you have a valid use case. However as we provide a single stream you need to respect the given aspect ratios, a horizontal view like on your screenshot won't work. There is a flexible configuration in development but it still limits to the video fixed aspect ratios.

You can hide the video by making the element non-visible, can you provide some more information on your requirements so we can come up with a tutorial how to achieve this.

**Comment by dispbd** [comment]
**1)** Sorry, apparently my screen confused you a little. There are two examples in one screen.
I do not need a horizontal view, but a vertical view, like on the right or left on the screen. That is, something like this:
![https://i.vgy.me/HGyJOy.png](https://i.vgy.me/HGyJOy.png)
Note that it is assumed that the participant will be able to scroll the vertical list of videos if it does not fit on the screen. I understand about the limitation of the sides (as I understand it, the video resolution is 1280x960), but is it possible to place more than 3 people vertically even at such a height? for example, place 6-9 people vertically, leaving empty space on the sides (it can be cut off or hidden by the background), albeit at the expense of video quality.

### Add. questions
**4)** What is the maximum number of people available at one conference? How many of them can be displayed in one video?

**5)** Due to the fact that there is only one stream, it is impossible to make a different display of the sorting of participants for different participants?
For example: first the speaker, then the local participant, then everyone else.
If yes, then it turns out that if there are many participants and the sorting is strictly fixed, then if you connect to the meeting late, the participant may not even see himself. And as I understand it, only a local stream will help in this case.

**Comment by unused** [comment]
If you only need a vertical set of participants on a side that's a layout we can work with, yet it needs to be inside the single video stream. We're pretty flexible with that, you can find some examples in the [interactive layout demo site](https://explore.eyeson.com/layout-demo).

We provide layouts with up to 10 positions, there is _no limit_ - techn. there is hard limit of around 100 - to participants.

You can assign users to fixed positions, additionally there is a "voice activation" flag that replaces automatically filled positions with active speakers (first-in-first-out by voice activity).

Let me know if you need any further details!

**Comment by dispbd** [comment]
Thanks for your flexibility.
We are satisfied that everything will be in one stream. I tested interactive layouts. Tried some layouts and backgrounds.
From my side, can I customize the vertical layout shown in my screenshot? If yes, then tell me how, please, because I did not succeed.
If customization is needed on your part, can you roughly estimate how long it will take? And do you require anything extra from our side?

About the "voice activation" flag - if it's enabled, does it replace the fixed user setting?

**Comment by unused** [comment]
voice activation only replaces positions that have no fixed participant assigned.

it won't take long to add a layout but beforehand I need to know how many participants should be shown on the right vertical view. can you please provide me with the fixed number you require?

**Comment by dispbd** [comment]
Since you write about the "right vertical view", then I understand correctly that the empty space will be on the left?
The fact is that in such rooms there can be from 2 to N participants on average. But since the room is limited to 10 participants, I would like to see a maximum of 10. That is, create several layouts, for example vertical-3, vertical-4, vertical-5 ...-... vertical-9 (that is, 7 new layouts). Leave the 10th participant under the background or screen sharing (empty space)
I understand that there may be too many layouts (in addition to the existing ones), so I suggest that you create only one separate property for setting layouts - vertical or verticalMode. With this mode, all users from 2 to 9 will be shifted to the side automatically, while leaving no empty spaces (except for the background or screen sharing).
If clarification is needed, I can describe in more detail.

**Comment by dispbd** [comment]
Excuse me, is it possible to indicate how much time you need to make changes?

**Comment by unused** [comment]
The new layout will be available with the next update that will most likely happen at the beginning of next week. I'll add some details when its available.

**Comment by unused** [comment]
We recently published a new update, the layout is available with the name `present-vertical-9`. Let me know if you have any further questions!

```sh
export ACCESS_KEY="..."
export USER_ID="..."

curl -s -X POST \
  -d "users[]=$USER_ID" \
  -d "layout=auto" \
  -d "voice_activation=true" \
  -d "name=present-vertical-9" \
  "https://api.eyeson.team/rooms/$ACCESS_KEY/layout"
```
