### ISSUE TITLE
Failed to show remoteStream

### ISSUE THREAD

**Issue by vahan1107** [eyeson-team/api#135]
Hi Eyeson team,

I want to implement eyeson in laravel9-vue3 project with vue3.

I have installed eyeson (npm i --save eyeson), tried to connect (create room and join), checked events, recognized that I didn't receive 'accept' event type. It ends {type: "exit", reason: "bye"} with this event.

Please check the attacked image, there are event logs and eyeson.js logs as well as one error:
Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: rtcp-mux must be enabled when BUNDLE is enabled.
![image](https://user-images.githubusercontent.com/29162041/193222099-5a3d63d2-3bc3-4bcb-89e8-2e481a86c60d.png)

Just FYI, I haven't any issue in my local project. It's happening only on our dev server.

Can you please tell me what's the problem and how to fix it?

Thanks in advance,
Vahan

**Comment by unused** [comment]
Hi there, can you please provide more information on your problem? Can you reproduce the problem every time within your test environment but not within your local setup? From your description the problem is on a client-side that does not depend on where your application is served from but on the browser client. Do you use any different browser there? Is there any other difference between your local and "dev" environment? Can you reproduce the problem using the default web UI provided by eyeson? Thank you in advance!

**Comment by vahan1107** [comment]
I have this issue only on the server, not on local. I checked also on Firefox browser, result is the same.
There is no any difference between my local and server codes and using the same eyeson API key.
On my local it's working perfect, I can connect, create room, join, also other users can connect and I can see video with all joined users, I did it same way as specified in 
[js docs](https://eyeson-team.github.io/js-docs/), set remoteStream to srcObject of the video element. But the same code on the server cause the error (error from my description):
> Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: rtcp-mux must be enabled when BUNDLE is enabled.

And the error cames from eyeson.js, not from my code. I checked that I'm using right API key, room right access_key. So I want to understand what is missing, I want to understand why the same code with the same credentials can't work on the server (FYI, there is no any ip whitelist problem)?

What you mean says "the default web UI"? Where I can find it?

If need any additional info, let me know.

Thank you in advance!

**Comment by unused** [comment]
> There is no any difference between my local and server codes [...]

As this is a client-side issue it is unlikely that the code is the same, except for the case there are either any issues with your content security policies or you are using any iframes.

You can find the link to the default web UI in the [join JSON response](https://eyeson-team.github.io/api/api-reference/#eyeson-room) at attribute `.links.gui`.

**Comment by vahan1107** [comment]
Hi there,
The code is the same both on my local and on the server (it's just me writing and uploading to the server).

I also tried this, so to speak, I translate the react code to vue3 from [your example](https://github.com/eyeson-team/react-web-gui-example/tree/main/src) , but the result is the same.

I checked gui link, it works perfect.

**Comment by unused** [comment]
Can you provide some more details on what's the result of this error in your web application? Do you see any video? Have you tried to use another browser client? Did you test the issue using a browser private window? Did you review the content security policies? This makes a major difference to using a local web server. Thank you in advance.

**Comment by vahan1107** [comment]
Hi all!
Enabled ssl on our domain and the problems disappeared.
Thank you!
