### ISSUE TITLE
add user to a room with api and no code

### ISSUE THREAD

**Issue by KlemoProd** [eyeson-team/api#139]
Hello,

I'm new in using Eyeson, and also in the development word.

My goal is to develop a webinar platform, indeed, I manage an audiovisual production company and we have a platform that already exists for streaming webinars. I want to add functions, and your solution seems to allow me to do what I want (group people on a videoconference meeting and have the ability to manage the layout with rtmp out).

I develop this platform in no code with Bubble.io. I use your solution thanks to the API, after some difficulties, I finally managed to create a room via the app.
 
Now I have a problem to add a new user in this newly created room.
 
I use the ID parameter, but this second user arrives in a new room anyway.
 
"room": {
"id": "<room_id>"
}
 
Can you help me on this issue?
thank you, 

![image](https://user-images.githubusercontent.com/120472195/207328190-19d2a9ce-ffd1-4ff3-a4e9-098501e7b096.png)

![image](https://user-images.githubusercontent.com/120472195/207328635-22ff8f37-1ec6-4fc4-a508-596777c39bcd.png)

**Comment by btreuer** [comment]
Hi @KlemoProd,
thank you for your question.
As far as I can see there is an error in line 2-4 . there is no "room"-object in eyeson API. please just call "id": {"<room_id>"},

Hope this helps
thomas

**Comment by KlemoProd** [comment]
Hi @btreuer,

Thank yo ! I will make the modification and tell you if it's working or not soon.

Many thanks,
Clem

**Comment by KlemoProd** [comment]
Hi @btreuer 

With your indication it's working now thank you !

An other problem now to use the POST /rooms/:access_key/layout

I create I room and use the link like this : 

![image](https://user-images.githubusercontent.com/120472195/207910341-600667f6-09de-4551-b50b-018d267f41cd.png)

And this is what I receive :

Raw response for the API 
Status code 401
{"error":"Invalid access key"}

I couldn"t find more information about this error and how to fix it.

Can you help me with that ?

Many thanks,
Clément

**Comment by btreuer** [comment]
Hi @KlemoProd, just saw that you used more than the free 1000 minutes and the key got locked. We unlocked your key so that you can keep on developing.
Looking forward to seeing your app!
Thomas

**Comment by KlemoProd** [comment]
Thank you @btreuer ! 

I'm trying now but still doesn't work with the Status code 401 and {"error":"Invalid access key"}.

Do you have more information about how to use this command ?

Thanks !

**Comment by btreuer** [comment]
Hi,
just noticed that you are using a colon ( : ) in front of your access key. the `:access_key` in our documentation means stands for a dynamic value. Just use `/rooms/[access_key]/layout` . This should do the trick.
Hope this helps
Thomas

**Comment by KlemoProd** [comment]
Hello @btreuer,

Thank you I manage to use it now ! Your advice help me a lot.

Where can I find more information about layout and layer action ?

My goal is to create picture in picture composition with one camera, one slide or PowerPoint and one background or foreground for create nice webinar and broadcast it trough RTMP.
I manage to add a .png picture, but the size is not good, and when I try a 1920x1080 it's not visible. 

Here is my json parameter : 

{

"url": "<url>",
"layout": "<layout>",
    
 "insert": 			
        						{
		 "icon": "<icon>",
 		 "title": "<title>",   
		 "content": "<content>"        
								}     
}


The other question is about the insert possibilities. It's possible to have another background ?  Like i can see in the layout example page in your website (https://explore.eyeson.com/layout-demo).

Thank you,
Clément
