### ISSUE TITLE
webinars

### ISSUE THREAD

**Issue by ashrafJebril** [eyeson-team/api#14]
Where can i find an API for WEBINAR

**Comment by unused** [comment]
You can use eyeson rooms to start any kind of video meetings, webinars, calls. There is no dedicated or different handling for webinars.

**Comment by ashrafJebril** [comment]
when i create the room there is nothing in the API allow me to make a webinar , my case i want a students to get in my video just as a viewer , is there any thing like that in the API?

**Comment by unused** [comment]
This depends on your application and particularly on the number of viewers, but there is no further requirement on the eyeson API. If you build your own user interface you can limit it to the viewing part by only forwarding the required stream to your user. If you have a higher number of viewers it's better to [broadcast the video](https://eyeson-team.github.io/api/api-reference/#broadcast), you can also find according helpers in the [eyeson JavaScript package](https://eyeson-team.github.io/js-docs/events/#broadcast) if you build you interface with it.
