### ISSUE TITLE
Auto layout with 2 users

### ISSUE THREAD

**Issue by natschz** [eyeson-team/api#141]
Hello,

is it possible to have the auto layout, where two users are side by side?
Currently if there are only two users in a meeting, the will only see each other, but we would like to have them side by side.
Setting the layout to custom and two sadly does not work for us, since at some point there might be more than two users.

**Comment by opusonline** [comment]
Hi!
I suggest to set `options[sfu_mode]` to `disabled` when starting a meeting. This will keep the automatic layout and when there are only 2 users in a meeting, they are displayed side-by-side.
See https://eyeson-team.github.io/api/api-reference/#eyeson-room for more information.

Please do not hesitate to leave a comment if you have any further questions.
