### ISSUE TITLE
Chrome problem to include meeting-room

### ISSUE THREAD

**Issue by hourlier96** [eyeson-team/api#18]
Hi,

I'm currently working on eyeson to have a meeting-room on our website (Vue.js / NUXT).
After i get the URL to the meeting room, i try to use a object tag to get the meeting.
It perfectly works on Firefox, but if i try on Chrome:

![Capture du 2019-07-04 14-49-08](https://user-images.githubusercontent.com/45850718/60667913-fa9fa800-9e6a-11e9-8dc5-0b9843bb7d8d.png)
The camera and micro can't setup so i can't do anything more.  If I try to activate manually the devices, the DOM exception occurs again. (see below)
I suppose it's because of security verification from Chrome, but i didn't find anything on the subject.

![Capture du 2019-07-04 14-49-37](https://user-images.githubusercontent.com/45850718/60667962-1b67fd80-9e6b-11e9-9fe2-4bc4bef1332f.png)
Here are the log of console.

Any help would be nice ! 
Thanks

**Comment by unused** [comment]
From the screenshot I guess you want to display the eyeson GUI on your website using an iframe. For this please ensure the [allow](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Attributes) attribute has a correct feature policy set and you are using a webserver also on a local environment or HTTPS on a hosted website.

```html
<iframe src="..." allowfullscreen allow="microphone https://app.eyeson.team; camera https://app.eyeson.team"></iframe>
```

Using Vue.js is a great choice :+1:. This also gives you a good base to build your own GUI. We provide [documentation](https://eyeson-team.github.io/js-docs/), [blog posts](https://techblog.eyeson.team/post/basic-web-gui/) and [examples](https://github.com/eyeson-team/react-web-gui-example), let us know if there is something missing.

**Comment by hourlier96** [comment]
HI !

Everything works perfectly now tahnks ! 
Had to replace object tag by iframe and to add the allow attribute as you described it !

See you
