### ISSUE TITLE
Eyeson on iOS

### ISSUE THREAD

**Issue by flodi** [eyeson-team/api#20]
Hi! I'm writing to know if ther is a iOS SDK in the works, or in any case how to you suggest to integrate eyeson with an iOS application.

thank you.

**Comment by unused** [comment]
Ahoi! We have currently no active milestone to release a SDK or framework that provides abstractions or helpers for the iOS platform. However you can build eyeson clients on any platform using [WebRTC](https://webrtc.org/native-code/ios/). When communicating with our services please ensure to use the endpoints provided by the room join response and also connect to real-time channels using SIP and WebSockets.

**Comment by Nkay** [comment]
@unused is there a milestone for this now? this is something we will need.

**Comment by unused** [comment]
We do not provide an iOS SDK at this point but can recommend to build a PWA instead.

**Comment by Nkay** [comment]
@unused this is no option, as we have to include a native plugin in our app. so, we cannot use eyeson?
