### ISSUE TITLE
how to remove user using api

### ISSUE THREAD

**Issue by mmayernik01** [eyeson-team/api#21]
Looking at the API documentation, i do not see how i can remove a user from an existing room.

What is the api call to do so.

**Comment by unused** [comment]
A room is an organization unit that provides a convenient way how to start a meeting. Users are added by joining them, as described in the API documentation, that creates access information for that particular meeting but not for any upcoming. Therefor you have full control about who will be able to join a meeting on-the-fly aka user management right at your hand.

**Comment by mmayernik01** [comment]
Hi,

I completely understand the joining aspect.

Through the API how can i programmatically remove an existing user from an existing room.

Is there a DELETE /rooms/access_key/users/:identifier

method that will remove the user from a room?

**Comment by unused** [comment]
Ahoi! There is no need to delete a user from a room as the user does only join a single session but has no access (with the given access key) afterwards. The room itself is used as an internal representation and is used to start meetings from there, and there is no reason to remove users. You can freely implement any kind of user management in you application.
