### ISSUE TITLE
Guest Can invite / redirects not working when room is ended

### ISSUE THREAD

**Issue by mmayernik01** [eyeson-team/api#22]
Hello,

Two questions:

1. Is there a property when creating a room that will not allow or hide the invite option?

2. When we end a room any user that is still in the room, sees the error.

_**Well.. We lost you fro a second. Try reloading the page or go Back to Account.**_   

If the room has been deleted, is there a way to force the user to be redirect to the exitUrl?

**Comment by unused** [comment]
Hi,

thank you for your questions, please note that those refer to the default web GUI we offer which is built to provide a general solution. For any custom features it's easy to create a custom GUI on demand.

1. We do not offer a configuration to hide quick join in the default web GUI.
2. We do not force-stop meetings or redirect users without interaction.

Best wishes!
