### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by khaledkamara** [eyeson-team/api#23]
i was tring to use your Rest API 
the /rooms/  => request
i have a 500 internal server error each and every time
i tried it from the code then from post man
always the same issue

**Comment by unused** [comment]
We did not succeed in reproducing your issue, can you ensure you can create a meeting using the example from the API documentation using `curl`?

```
curl -X POST \
  -H "Authorization: YOUR_API_KEY" \
  -d "user[name]=Bob" \
  "https://api.eyeson.team/rooms"
```
