### ISSUE TITLE
Expiring meetings, logo size, locales and meeting minutes

### ISSUE THREAD

**Issue by jseverinson** [eyeson-team/api#26]
Hi Eyeson team, thanks for a great service. I was directed here after emailing your support team. I have four issues/questions.

1. The meetings I create seem to expire after a short while, rendering the API response "Access key expired". Sometimes this has even happened just minutes after creation. Could you help me understand when and why rooms expire? As a follow up, is it controllable somehow?

2. The custom logo in the room creation is a nice touch. Is there any guidance in terms of size? I see that the CSS locks it to a height of 2rem.

3. Which locales are available? My service is for users in Sweden and if you don't have that available perhaps I could help with translation?

4. Would it be possible to query the API to get the number of minutes the meeting room was used?

Thank you very much!
John

**Comment by unused** [comment]
Hi there, and thank you for your questions, let's see:

1. You don't have to create a room upfront, simply request it when a user wants to start/join. If you start a meeting without anyone participating, it will quite soon close down again and you end up with an invalid access. Depending on different states, this timeout is about 2 minutes.
2. If available I'd recommend to go for an SVG image so it scales nicely e.g. if some user has a larger font-size set. However if not available an image with size around 32px will do fine.
3. Thank you for your offer, I'm happy to forward your request. We currently provide the GUI only in english and have some translation for sure in german as we are austrian based :)
4. Yes, you can setup the webhook to receive any updates on a rooms. This will provide you the starting time, participants joining, as well as the end time. Note: A single webhook is enough, every room update related to your API Key will be send there.

Please do not hesitate to open another issue if you have any questions, best wishes!
