### ISSUE TITLE
UI for guests is in English language

### ISSUE THREAD

**Issue by brjasha** [eyeson-team/api#27]
Hello,

I use API: "POST /guests/:guest_token?name=Abc" to join a room as named guest - using links.gui from response. It is not documented, but I have tried to append parameter "user[custom_fields][locale]=de" to the post request - just like it works for room creation. Unfortunately, UI is still displayed in English. Is this parameter supposed to work for guests or not? Is there another way to show localized UI for guests?

**Comment by unused** [comment]
I am afraid we do not provide the Quick Join login in a different language, however I'll forward your request so we may add this to our roadmap. On any updates I will leave a short comment.

**Comment by brjasha** [comment]
Thanks!

**Comment by unused** [comment]
You can adapt the locale for a guest user by providing `custom_fields[locale]`. In order to enforce a different language for the guest join link add an additional parameter `&locale=de`. If you have any questions please do not hesitate to leave a comment.

**Comment by brjasha** [comment]
Unfortunately, I cannot confirm, it works.
I'm doing request like this to get GUI link for guest:
POST ~/guests/:guest_token?name=Sergej&locale=de

I also tried to append &locale=de to the GUI link, which I'm getting after mentioned POST request. Neither way it shows me UI in German.

**Comment by unused** [comment]
You can adapt the locale for a guest user by providing `custom_fields[locale]` in your POST request. The `locale` GET parameter is for the guest-link.

**Comment by brjasha** [comment]
Sorry, was bit unclear. Works this way, thank you.
