### ISSUE TITLE
Deactivate room features for guests

### ISSUE THREAD

**Issue by brjasha** [eyeson-team/api#28]
Hello,

is it possible to deactivate certain room features for guests in eyeson own web UI using some API parameters (similar to options[recording_available])? For example, that guests can't:
1. Post reactions
2. Share their screen
3. Mute all
etc.

**Comment by unused** [comment]
Please refer to the [documentation](https://eyeson-team.github.io/api/api-reference/#eyeson-room) on which configuration can be done. There is one missing `options[reaction_available]` to control to show GIF reactions in the default UI. I'll update documentation asap. Please note that you can easily create a custom user interface on your own, please find further details on our [developers site](https://www.eyeson.com/developers/). Best wishes and stay safe!

**Comment by brjasha** [comment]
Hello,

Unfortunately, this option doesn't seem to work: options[reaction_available]=false
GIFs are still available in UI of the room.

**Comment by unused** [comment]
Please check the parameters send, I've just tested the option and it seems to work fine. You can use the following snippet to check the configuration:

```sh
curl -v -X POST \
  -H "Authorization: <your-api-key>" \
  -d "user[name]=eyeson" \
  -d "options[reaction_available]=false" \
  "https://api.eyeson.team/rooms"
```

**Comment by brjasha** [comment]
I'm sorry, you are right. It truly works... probably, we have messed-up something.
