### ISSUE TITLE
Need the API names 

### ISSUE THREAD

**Issue by alosharma** [eyeson-team/api#29]
We want to build an video conferencing solution with our ERP application where our user should be able to:
 - schedule the video conferencing
 - record the conference.
 - presenter should be able do screen share.

Please let us know if this will be possible APIs. and which APIs I should use for
1. createRoom
2. StartSession
3. EndSession
4. Join Room
5. Screen Share
6. Record session
7. Mute/unmute participants.

**Comment by unused** [comment]
Please refer to the [api documentation](https://eyeson-team.github.io/api/) for any details on our provided services. You can have a good overview on our [developers site](https://www.eyeson.com/developers/) which also contains pricing and further resources. If you have any concrete problem with our service do not hesitate to create an issue on GitHub. Best wishes and stay safe!
