### ISSUE TITLE
Eyeson - using ASP.NET / Blazor

### ISSUE THREAD

**Issue by redowl3** [eyeson-team/api#30]
Further to a conversation with Christoph, who asked to conitnue on Github.

We are looking to use Eyeson with a Blazor application and would be very grateful for any help to get started.

**Comment by unused** [comment]
It is recommended to use the [JavaScript library](https://eyeson-team.github.io/js-docs/overview/) as it contains many helpers that make development of a custom GUI very straightforward. You can also have a look on the [simple react example](https://github.com/eyeson-team/react-web-gui-example).

Without library please have a close look on the details received from a room. Setup a connection with the provided SIP and Websocket credentials. Use the provided stun and turn configuration to setup your WebRTC connection and use SIP for signaling.
