### ISSUE TITLE
Custom live streaming system

### ISSUE THREAD

**Issue by sowrensen** [eyeson-team/api#31]
Hi, I want to build a one-to-many live streaming system. As per your documentation, for broadcasting, the required parameters are `platform`, `stream_url`, and `player_url`. Now, what if I don't want to use YouTube or Facebook as a platform but my own application? Do I still need to configure a RTMP server? Pardon me if I am missing something. 

![Screenshot_20200425_145442](https://user-images.githubusercontent.com/13097375/80275776-462a8780-8705-11ea-8519-2869495b25a4.png)

**Comment by unused** [comment]
Hi there, for this purpose you can use the identifier "generic" and your custom stream url. The player URL is optional and serves only as a forwarding attribute, so you can store and provide a URL for your users (received via event messages in meeting), you might not need it I guess.
