### ISSUE TITLE
Questions about eyeson API

### ISSUE THREAD

**Issue by key-sn** [eyeson-team/api#33]
I got [this link](https://github.com/eyeson-team) when I made an inquiry from the HP inquiry form, but I do not know the inquiry form, so I will ask you here.

```
I have four questions.

If you only use the API,

1. How many video rooms can I create?
2. How many people can join the video room?
3. How long can I use the video room?
4. Is it possible to add an authentication function to join the video room?
```

I am looking forward to receiving your reply.

Kei

**Comment by unused** [comment]
You can create as many rooms as you want, yet there is a time limit, see the [pricing overview](https://www.eyeson.com/developers/#pricing) for details. There is no actual limit for the users that join, also the time limit counts per meeting, not per user. However the current max number of participants shown on video podium is 9 and there is a soft limit of 100 users that can participate using audio. The meeting has no time limit.

You can easily use your own authentication service for your video meetings - simply join a room on your service when authentication is verified and forward the user.

**Comment by key-sn** [comment]
@unused 

Thank you for your answer.

I have additional questions, so I hope you can answer them.

1. Is it included in the price calculation even if there are no people in the meeting?
2. Is it possible to join the meeting without entering a password or authentication information in the request header other than the URL?
Because even if I authenticate within my application and transition to the meeting, I think that the URL can be easily found as long as I use the browser, and it is possible that an outside person can easily join the meeting.

**Comment by unused** [comment]
You're welcome! To your new questions: There is no need to start a meeting when no one is joining. Simply start a meeting on the fly. There is a minimal duration calculated (at the moment it is around two minutes) also for an empty meeting.
No person that does not have the link can join the meeting, guessing the link is as likely as guessing  any other credentials (e.g. password). The access is generated on your request and only valid for the time of the meeting.

**Comment by key-sn** [comment]
Thank you!

I was able to understand a lot about the functions of eyeson's API. 
We will consider using it again.

**Comment by unused** [comment]
:sunglasses: Do not hesitate to contact if you have any further questions!
