### ISSUE TITLE
Video stream on iOS (cordova app or mobile safari) not showing up

### ISSUE THREAD

**Issue by elmartino** [eyeson-team/api#34]
Hi,

I wonder why my videostream on safari and cordova app is not showing up.

this is how my video tag looks like

`<video #video preload="auto" autoplay autopictureinpicture="false" playsinline muted></video>`

I set the source from js code in angular: `this.video.nativeElement.srcObject = this.state.stream;`

On Desktop this is all working fine.

Any help would be appreciated!

Martin

**Comment by unused** [comment]
Note that this is a general issue auto-playing your video on an iOS device. Unfortunately there are some known issue to Safari, especially on mobiles that do not [play nicely](https://github.com/webrtc/samples/issues/929). As your video tag looks good, I'd suggest to test if `play()` called on your video element solves the issue.

**Comment by elmartino** [comment]
Thanks! Working like a charm!

**Comment by elmartino** [comment]
I was a little bit too early, in iOS and Android web it's working, but in iOS and Android cordova not.

i get joined in the meeting (fullscreen), but the cam/mic isn't working. Any ideas what could be wrong? I have NSCameraUsageDescription and NSMicrophoneUsageDescription in my config.xml for iOS. 

On Android app, the video is still not starting.

**Comment by unused** [comment]
We are happy to help with any issues regarding eyeson or give some help using web standards. For any problems related to Apache Cordova I have to ask you to look into its resources and request help in the Cordova communities instead.

A hint anyways: If you already have a working web app and require your software to be available in Play Store and App Store have a closer look on Progressive Web Apps (PWAs).
