### ISSUE TITLE
What event do i need to send to start screensharing?

### ISSUE THREAD

**Issue by elmartino** [eyeson-team/api#35]
Hi,

I can't find the documentation to start screensharing within my application.
Can you tell me how to achieve this?

Thanks!

Martin

**Comment by unused** [comment]
Please have a look on the [screen capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API), the media stream received can be handled the same as the one you receive from camera. Let me know if you need any further help.

**Comment by elmartino** [comment]
Thanks for the pointing in the right direction!

I am able to capture the stream and see my own screen in the video tag:
`    
  const stream = await this._navigator.mediaDevices.getDisplayMedia({ video: true });
   this.video.nativeElement.srcObject = stream;`

But how can i change my eyeson stream so that other users will see my screen?
I tried: `      eyeson.send({
        type: 'change_stream',
        stream: stream,
        video: this.state.video,
        audio: this.state.audio,
      });`

But without success.. I think i'm almost there... Hope for your help!

**Comment by unused** [comment]
If you just want to replace your current video with the screen capture, you can use the internal event `eyeson.send({ type: 'start_screen_capture', audio: true, screen: true })` and `eyeson.send({ type: 'stop_presenting' })`. Hope this works for you.

**Comment by elmartino** [comment]
@unused after this command 
`eyeson.send({ type: 'start_screen_capture', audio: true, screen: true })`
i get:
`eyeson.js:51 ScreenCaptureEvent TypeError: Cannot read property 'getVideoTracks' of undefined`

is this feature also documented somewhere?

**Comment by unused** [comment]
Sorry, maybe I missed something as I just had to look it up. I'll provide some example as soon as possible.

**Comment by elmartino** [comment]
No problem, that would be great!

**Comment by elmartino** [comment]
@unused did you already found some example? Thanks!

**Comment by unused** [comment]
I've added a very basic implementation to the [react web gui example](https://github.com/eyeson-team/react-web-gui-example/commit/849de7cb4289107a2bb3b77261852b71c23136f1). If you use this variant it also takes care to set the layout to the single user who is sharing and set it back afterwards. For sure you can also just replace a single position on the video podium as well.

**Comment by elmartino** [comment]
It's working great! Thanks for the example!
