### ISSUE TITLE
How to use the eyeson utilities?

### ISSUE THREAD

**Issue by elmartino** [eyeson-team/api#36]
I tried the utilities according to your documentation, but it's not working

const deviceManager = new eyeson.DeviceManager();

It says DeviceManager is not a constructor. Same for the FeatureDetector

any help would be great!

**Comment by unused** [comment]
This depends on how you use the JavaScript package. I guess you'll need `import { FeatureDetector, DeviceManager } from 'eyeson';`

**Comment by elmartino** [comment]
Thanks, that was it!
