### ISSUE TITLE
Sample c# code for eyeson video conferencing

### ISSUE THREAD

**Issue by mikeobasuyi** [eyeson-team/api#37]
Good day, can we get a sample c# code for eyeson video conferencing? Something easy to test and then can later modify to get started with. 
Thank you

**Comment by unused** [comment]
Ahoi! You can use the minimal example from the [API documentation](https://eyeson-team.github.io/api/getting-started/) to start a meeting:
```sh
$ curl -X POST \
  -H "Authorization: YOUR_API_KEY" \
  -d "user[name]=Bob" \
  "https://api.eyeson.team/rooms"
```
The API is a limited set of REST endpoints you can easily handle in any language. We currently do not provide a specific package for C#. Best wishes!
