### ISSUE TITLE
Host can see every participant. Participants can see only host

### ISSUE THREAD

**Issue by Dronnikkl** [eyeson-team/api#38]
Hello! I am using eyeson REST and JS API for creating room, showing and sharing video stream. I want host user enable to see everybody in room. But participants can only see the host in a a same time. How can I solve it? Thank you

**Comment by unused** [comment]
eyeson is based on a [single-stream technology](https://help.eyeson.team/eyeson-room/en/articles/735255-what-is-single-stream-technology) which has many advantages but - as the name suggests - does not provide multiple streams to show and hide by user role. Best wishes!

**Comment by Dronnikkl** [comment]
Thank you! @unused Can i use two eyeson js instances to work with two rooms in a same time? So I will have two streams in two different rooms. One for all participants and one for host?

**Comment by unused** [comment]
You can handle this within your application, however keep in mind that then you are running two video calls at once just to provide different streams, that might be an overhead.
