### ISSUE TITLE
How to do some actions

### ISSUE THREAD

**Issue by Antoni-Lopez** [eyeson-team/api#39]
Hello,

I created a room but I'm unsure about the following tasks, documentation doesn't really explain how to:

1) Add a new user, but not as a guest user. A user who has the same role as the one created at the room creation.
2) URL to be used to point to the meeting for this new user. What parameters/IDs should I use in the POST data?
3) After a couple of minutes of inactivity, I found out that the room is gone. If for example the last user in the room decided to restart this "dead" meeting, he gets a page saying the room is gone. Do I have a way to query if the room is already gone (so I could create a new one) or otherwise allow the user to enter the meeting?
4) I tried to get a room details, but I keep getting "401: Not authorized". I tried different ways, but none works:

- https://api.eyeson.team/rooms/:my_access_key   (with and without the Authorization header)
- https://api.eyeson.team/rooms/my_access_key   (with and without the Authorization header)

Could you please tell which is the right one (and if I need to include the header) or anything I should take into account?

Kind regards

**Comment by unused** [comment]
Hi! You can add a user as described in the [API documentation](https://eyeson-team.github.io/api/api-reference/#eyeson-room) using the `/rooms` endpoint (POST Request). Provide the same identifier `id` to ensure your participants will end up in the same room. The links provided in the response will be unique by user. Please start a meeting on-the-fly and forward your users, there is no reason to do this upfront, meetings will expire after a short period of time if no participant joins. If you need e.g. scheduled meetings, you can handle this in your application and just request the meeting when a user is ready to join.
In order to receive room details, use the access token of a user you receive when requesting a new meeting, the API key (via Authorization Header) is not required there.

**Comment by Antoni-Lopez** [comment]
Hello,

I could finally add an user to a room, and also know when a room is ready or I should create a new one. What I can't obtain is the room details when doing the GET method.
I'm calling the URL like this, which is quite straight forward (for .NET platform):

Dim uri As New Uri("https://api.eyeson.team/rooms/:ObGr1z7rnlFC7qjTcZdEdW4Z")
Dim request As System.Net.HttpWebRequest = System.Net.HttpWebRequest.Create(uri)
request.Method = System.Net.WebRequestMethods.Http.Get
Dim response As System.Net.HttpWebResponse = request.GetResponse()
Dim reader As New IO.StreamReader(response.GetResponseStream())
Dim DataBack As String = reader.ReadToEnd()
response.Close()

Where "ObGr1z7rnlFC7qjTcZdEdW4Z" is a valid access_key sent back from your platform when my new room was created.
I keep getting "Error 401: Not authorized", so I don't know what I'm doing wrong. Could you please give some light to it?

Many thanks

**Comment by unused** [comment]
Ah I see - sorry, I did not get this from your last message :crying_cat_face: Skip the `:` it has to be `https://api.eyeson.team/rooms/ObGr1z7rnlFC7qjTcZdEdW4Z`, so you receive an `{"error":"Access key expired"}` as the key has expired for sure. You will commonly fetch meeting details for a participant in the user interface, it is also safe to do it client side as it does not require an API key. You can also gather an idea about the client-side communication if you start a meeting at eyeson (using default GUI) check the requests (e.g. via browser developer tools network tab). The default GUI is btw. also available via API (see links in response) and is a good option to kickstart your project.

**Comment by Antoni-Lopez** [comment]
Hello,

I finally got room details when fetched during the valid period of an active room. But if I fetch this information after a couple of minutes of inactivity, then what I get is a web exception (actually breaks my code) with error code "410: Gone", not JSON data including "{"error":"Access key expired"}". It forces me to wrap the request within an error handler. Instead, if I launch the very same URL with my browser, it actually shows "{"error":"Access key expired"}" as you mentioned.

Cheers

**Comment by Antoni-Lopez** [comment]
Hello,

We developed a test page which uses an iFrame to show up the video meeting, and it's working fine in Chrome and Firefox, but it isn't in Safari. Another user in this issues section (@salgadoperez) said that adding this to the iframe:

allowfullscreen allow="microphone https://app.eyeson.team; camera https://app.eyeson.team"

but it's not working for me.

Do you know what attributes I should use in the iFrame for Safari?

Cheers

**Comment by unused** [comment]
I'd recommend not to use an iframe in first place. The attributes `allowfullscreen allow="microphone https://app.eyeson.team; camera https://app.eyeson.team"` however are fine. What do you mean by "it's not working for me"?

**Comment by Antoni-Lopez** [comment]
Hello,

What I meant was that, within an iframe, Safari shows me that camera and micro can't be accessed, so I can't launch your URL within an iframe, I'm forced to open up a new window. It's a pity because i wanted to have the service iframed and also hide the eyeson URL to the user's view.

We'll see if we can manage all this with webviews within webapps, for both Android and iOS.

Cheers

**Comment by Antoni-Lopez** [comment]
Hello,

We successfully added a webhook for room_update, but we are trying to catch the information sent to the page we specified in the URL parameter. Because we didn't know if we were to receive values in Request.Querystring or Request.Form, we checked both, but no information is sent this way.

1) How should we collect the information sent by your webhook?, is it in JSON format?
2) In case we decide to cancel a webhook, should we call the webhook and leave the URL parameter empty?

Another problem found is when trying to send a message to a room. We tried these 2 ways (both sent back a "Forbidden"):

1) Even though we don't want to send a message to the chat section, we tried:
$ curl -X POST \
  -d "type=chat" \
  -d "content=this is a message" \
  "https://api.eyeson.team/rooms/My_Access_Key/messages"
We need to know what is failing (we didn't include the Authorization header), and also what we have to specify in "type" to send a normal message on screen, not to the chat section.

2) In case the "messages" API was only intended for chat communication, we tried also:
$ curl -X POST \
  -d "insert[content]=this is a message" \
  -d "z-index=1" \
  "https://api.eyeson.team/rooms/My_Access_Key/layers"
Again, without Authorization header. It didn't work either, we don't know whether we need to specify some other parameters since we used "insert[content]". We are just looking for a way to send a normal message to be shown on the screen, to an attendee, so please tell us an example of usage.

Finally, we successfully delete a room on the fly, but because it was over a video meeting on a popup window, we don't have any control over the content (it shows eyeson's room URL). What we saw, after the deletion, was that the screen content changes to something like "We lost you for a second...". Would it be possible to send the user to a custom page or change somehow the content shown?

Thanks for your help, but after spending some time with your APIs, I believe the documentation should give some more details and examples, because we just keep trying things due to the lack of explanations.

Cheers

**Comment by unused** [comment]
Thank you for your feedback, as stated in the documentation webhooks provide a JSON document with the information. I'll check the documentation and add any missing details.

If you receive a response that informs you the access key is no longer valid the meeting is certainly gone as no one joined it. Please ensure there is some active participant. For sure you can communicate with the API on server-side but just to make sure there is no misunderstanding: In most cases communication using the access key is done client side, in case of web applications via browser. That's why the participant can stick to the access key valid for the meeting rather than depending on the API key.

We do not allow to redirect users to external sites without their action but you can set an exit URL to specify the location a user goes when deciding to leave the meeting via exit button.

**Comment by Antoni-Lopez** [comment]
Hello,

The problems found when trying to send a normal message were right after a room created, so for this reason I mentioned it was a valid AccessKey, I had clear in my mind it couldn’t work if a room is gone. Please provide a valid example of normal message sending, because what we tried with a valid AccessKey didn’t work. We don’t even know if this could be accomplished using the layers or the message API. This is important to us because we need to communicate things to the users in a room at real time.

Also, tell us please how a webhook sends the information back. We know it is in JSON format, but we don’t know where/how to collect the data, and also how to cancel a webhook.

Best regards

**Comment by unused** [comment]
You can use the layers endpoint to inject media into the video stream but it might be not a good choice to communicate. Messages provide an interface to the real-time channel but this does only make sense if you build your own user interface, which is what I'd recommend as it simply integrates in your application seamless and you do not have to bother about exchanging information (or dealing with iFrame issues).

If you answer to GitHub notifications, it creates new (public available) comments but does not forward any email messages.

Best wishes!

**Comment by Antoni-Lopez** [comment]
Hello,

We still don't know why we can't send a simple message or even upload a PNG image to a new room. At creation time, we specified **options[sfu_mode]=disabled** and right afterwards we tried out these two ways:

$ curl -X POST
-d "insert[content]=this is a message"
"https://api.eyeson.team/rooms/My_Access_Key/layers"

After failing the above method, we tried also the following (having a valid and accessible image of 1280x960 px):

$ curl -X POST
-d "url=https://www.mysite.com/myimage.png"
"https://api.eyeson.team/rooms/My_Access_Key/layers"

Please, check them out and let us know why none are working and how we should make the call.

Cheers

**Comment by unused** [comment]
Works pretty well, please double check your image URL is public available

```sh
$ curl -X POST "https://api.eyeson.team/rooms/.../layers" -d "url=https://app.eyeson.team/static/media/logo-overlay.ad882bed.png" # set overlay
$ curl -X DELETE "https://api.eyeson.team/rooms/.../layers/1" # clear overlay
```

**Comment by Antoni-Lopez** [comment]
Hello, thanks for trying it out.

Unfortunately it is not a matter of the image URL, we also tried yours, we keep getting back a "403: Forbidden", both now and the past days.

Could you please try it using our API key?, just to make sure we don't have any service or anything blocked.

Cheers

**Comment by unused** [comment]
Hi, there is no restriction on any API key - use an active access key of any meeting and you're good to go.
