### ISSUE TITLE
Delay in video?

### ISSUE THREAD

**Issue by elmartino** [eyeson-team/api#40]
Hi,

Some users are complaining about some delay of 1-2 sec. in the video. If the same users uses a video meeting tool of an eyeson alternative (zoom, whereby etc.) they don't have this delay.

I'm using the javascript sdk in my angular application.

Thanks in advance!

**Comment by unused** [comment]
Ahoi, this is a great question, unfortunately it is a quite complex topic. From a technical point of view other video services have a similar delay however show the local stream of the user to give the impression that the connection is great. We did something similar but merged it into the video, removed it some time ago to avoid issues with positioning. There is [an article in our help center](https://help.eyeson.team/eyeson-room/en/articles/1330787-how-is-the-video-conversation-synchronized-with-video-and-audio) that goes into further details, you can also find more details in related articles.
