### ISSUE TITLE
More customization for gui?

### ISSUE THREAD

**Issue by elmartino** [eyeson-team/api#41]
Hi, is it possible to disable chat and other features in gui? I can disable some, but not all features.

Thanks in advance!

Regarda

**Comment by unused** [comment]
Ahoi, we did not consider to deactivate the chat as it is very basic and crucial to communicate in case someone has problems with the local devices or similar situations.

**Comment by elmartino** [comment]
Thanks, yeah but i have my own realtime chat in my application via my own websocket. Now my customers will get confused wich chat to use

**Comment by unused** [comment]
I see, in this case it makes sense. I'll check if we can have an option for this.

**Comment by unused** [comment]
The option will be included in next API release which will come up this week. I'll leave a comment when the configuration is published.

**Comment by opusonline** [comment]
Hi, good news! This feature is now released and working. The chat is hidden when `options[custom_fields][hide_chat]`is set to `true` via API.

See https://eyeson-team.github.io/api/api-reference/#eyeson-room
