### ISSUE TITLE
toggleAudio not working on iOS safari

### ISSUE THREAD

**Issue by elmartino** [eyeson-team/api#42]
Hello,

I have a problem with toggleAudio to mute the microphone (from the react example) in iOS safari.
`  toggleAudio() {
    eyeson.send({
      type: 'change_stream',
      stream: this.state.localStream,
      video: this.state.video,
      audio: !this.state.audio,
    });
    this.state.audio = !this.state.audio;
  }`

It is working on desktop. toggleVideo is working like expected (also in iOS safari). Do i need to  do something special to make this working in iOS?

Thanks!

Martin

**Comment by unused** [comment]
Thank you, I'll check if there is an update missing :+1:

**Comment by opusonline** [comment]
Hi,
Thanks for reporting!

To avoid issues with iOS, you should use another strategy to toggle audio.

The eyeson plugin provides the `StreamHelpers` class with `enableAudio` and `disableAudio` functions.

Here's an example: https://github.com/eyeson-team/react-web-gui-example/blob/master/src/App.js#L48

Best regards,
Stefan
