### ISSUE TITLE
DELETE API is not working

### ISSUE THREAD

**Issue by vkeenala** [eyeson-team/api#46]
Dear eyeson team,

I am trying to use DELETE API, but getting 403 Forbidden.

DELETE /rooms/:identifier # force to stop a running meeting
  HEADERS Authorization
  RESPONSES 204 NO CONTENT, 404 NOT FOUND, 400 BAD REQUEST

ex: https://api.eyeson.team/rooms/:identifier

what is the :identifier and what value i have to pass in that place?

i tried by passing access_key, room.id. But not working and giving 403 Forbidden.

Kindly help on it.

Regards
Venkata.

**Comment by unused** [comment]
Please use the [room identifier](https://eyeson-team.github.io/api/api-reference/#eyeson-room) `{ "room": { "id": "..." } }`.
