### ISSUE TITLE
Web hooks is not working properly.

### ISSUE THREAD

**Issue by vkeenala** [eyeson-team/api#47]
I tried the webhooks but getting 403 Forbidden
ex:
https://app.eyeson.team/webhooks?url=XXX&types=recording_update
HEADERS Authorization.

Please help on how to use webhooks.

Regards
Venkata.

**Comment by unused** [comment]
Did you use proper HTTP method `POST`?

```sh
$ curl -X POST \
  -H "Authorization: YOUR_API_KEY" \
  -d "url=XXX" \
  -d "types=recording_update" \
  "https://api.eyeson.team/webhooks"
```

**Comment by vkeenala** [comment]
Thank you Christoph Lipautz.

Now its working fine.
