### ISSUE TITLE
How to handle expired token

### ISSUE THREAD

**Issue by gsinghab2** [eyeson-team/api#48]
Hi,

We are displaying eyeson meeting in an iframe and sometimes when meeting token expires, it is taking users to eyes on expiry page. Is there a way to redirect users to our own page so that we can give a personalized experience to the user.

Thanks,
-Gautam

**Comment by jhintringer** [comment]
Hy Gautam,

you can simply run a php script in the iframe beforehand, that calls the eyeson api to get the room details. If everything goes right, you'll get the gui-link to redirect to, else you can display an error message.

That's the way, we did it.

Hope, this helps.
Kind regards,
Jochen

**Comment by gsinghab2** [comment]
Thanks Jochen for your response. We also have a backend server that returns the meetingroom  details. When there is an issue and no meeting room is returned, we can handle it properly and show user some error message instead. The problem is we have is, sometimes the token that our backend returns can expire in which case we are getting the RIP eyeson page. Instead we want to redirect user to our page. We are looking for something similar to "exit_url"  option for expiry (expiry_url?).

**Comment by unused** [comment]
Hi there, thanks @jhintringer for the reply. There is no need to require a meeting room upfront @gsinghab2. Join the meeting and forward the user, the access token will never be expired. For sure this action is always handled server-side not to expose your API key. Best wishes!
