### ISSUE TITLE
New API "End for All" causing issue for us 

### ISSUE THREAD

**Issue by gsinghab2** [eyeson-team/api#49]
Hi,

With new API we host is getting a prompt to end meeting for all upon clicking of which the quests are redirected to following page.
![image](https://user-images.githubusercontent.com/40739654/83992027-71afad00-a914-11ea-9b34-ae15b6458ac4.png)
Is it possible to redirect to a custom page or customize this page?

**Comment by unused** [comment]
Thanks for the heads-up, it should respect the `exit_url` option but it seems it doesn't. We will look into this issues asap.

**Comment by gsinghab2** [comment]
@unused any update on this issue?

**Comment by unused** [comment]
The issue is fixed with an upcoming release that will be published soon.

**Comment by unused** [comment]
Please use the `exit_url` option to specify the target of the exit page action. However we do not allow to directly redirect participants when a meeting has ended without their interaction. The button label will be updated soon with a more generic message. Best wishes!

```sh
$ curl -v -X POST \
  -H "Authorization: <API-KEY>" \
  -d "user[name]=username" \
  -d "options[exit_url]=https://eyeson.com/developers" \
  "https://api.eyeson.team/rooms"
```

**Comment by opusonline** [comment]
Hi, good news!
We have renamed the button from "Back to account" to "Close & continue".
