### ISSUE TITLE
webhooks don't fire

### ISSUE THREAD

**Issue by yflorezr** [eyeson-team/api#50]
![Captura de Pantalla 2020-06-11 a la(s) 6 49 29 a  m](https://user-images.githubusercontent.com/13585334/84382265-041fad00-abb0-11ea-863b-d4c90d0804e6.png)

Hello eyeson team,

I have the webhooks configured to notify my server in "recording_update" and "room_update", but the request is never received

**Comment by unused** [comment]
Ahoi! The `types` parameter should be send as string rather than a list so no types were registered for your webhook. No worries, I corrected it for you and I filed an issue to respond with an error for an empty list and also accept lists. Best wishes!

**Comment by yflorezr** [comment]
webhook notifications do not reach my server

**Comment by yflorezr** [comment]
I'm logging into my endpoint and eyeson api never notify me, webhooks don't seem to be working

**Comment by unused** [comment]
You have setup a webhook for `recording_updates` so you'll receive data as soon as you stop a recording by any started meeting from your API key. I've just tested the recording updates and the webhooks are sent properly. Please ensure your endpoint does handle HTTP method POST and handles the JSON formatted body properly. Best wishes!

**Comment by ragheeddamaj** [comment]
Same issue! I registered a webhook and logging everything received by this hook. but eyeson never send me any update

**Comment by ragheeddamaj** [comment]
Do the endpoint has to be HTTPS (or HTTP is enough) ?

**Comment by yflorezr** [comment]
I could never get it to work .. I think the documentation is not the clearest

**Comment by yflorezr** [comment]
I had to do a very manual implementation to be able to extract the recording

**Comment by ragheeddamaj** [comment]
If webhook is not working, how can I extract the user_updates (i need an array of reporting for every user when he enters the meeting and the duration)... or I can not do this with Eyeson?

**Comment by unused** [comment]
Hi there - webhooks should be fine, we cannot see any troubles in our logging. We also use it for several services ourselves and do not see any problem there.
Do you have troubles reading the data or did you not receive any request (checking the webserver access/error logs) at all? 

We'll discuss further improvements on the webhooks next week. For a quick help we will include timestamp and response code of the last sent webhook that you'll be able to lookup asap. Best wishes!

**Comment by ragheeddamaj** [comment]
Dear, 

How can i see the log for each participant in the meeting (every time he enters and left the meeting)

Thank you

**Comment by unused** [comment]
We don't track the API users participants but you can easily build your own custom user interface and do so. Best wishes!

**Comment by unused** [comment]
We've added additional information to the webhook endpoint so you can fetch the [last sent request timestamp and response code](https://eyeson-team.github.io/api/api-reference/#register-webhooks).

**Comment by Pabbly** [comment]
I am also generating a webhook for room update but not getting any response attaching images for Post and Get method for the webhook via the postman. passing my API key in Header as Authorization 
**Post Webhook**
![2020-12-22_11h10_28](https://user-images.githubusercontent.com/36149152/102853936-60109b80-4447-11eb-918a-3cb581b8fb0f.png)
**Get  Webhook**
![2020-12-22_11h11_40](https://user-images.githubusercontent.com/36149152/102853976-79194c80-4447-11eb-9cc9-4fe3cb4b98c9.png)

and also passing the types as string 
![image](https://user-images.githubusercontent.com/36149152/102854094-c72e5000-4447-11eb-98af-275704cb0de5.png)

**Comment by unused** [comment]
Please ensure your endpoint can handle POST requests and that you should only create a single Webhook. We do not see any current issues with Webhooks. How many meetings did you start via API in between the Webhook creation and the check for last request?
