### ISSUE TITLE
Get recordings by room id error 500

### ISSUE THREAD

**Issue by yflorezr** [eyeson-team/api#51]
![Captura de Pantalla 2020-06-11 a la(s) 6 54 57 a  m](https://user-images.githubusercontent.com/13585334/84382584-785a5080-abb0-11ea-8eab-8aebb1bd1722.png)

**Comment by unused** [comment]
Thanks for the feedback, should not respond with 500 but 404 for sure. You'll receive a proper recording identifier via webhook.
