### ISSUE TITLE
Internal Error 500 & Question

### ISSUE THREAD

**Issue by Louiesmithsts** [eyeson-team/api#52]
Hey Guys, 

I am trying to embed your API into a WPF program and I wanted to know if it was possible to pull a person video feed if a room was created? as in can, I pull from the API the video URI of all or one recipients.

Also when I used your API I get internal error 500 when following the first two steps from your documentation. 

Kind Regards

**Comment by unused** [comment]
Hi there! eyeson is based on its unique [single stream technology](https://help.eyeson.com/eyeson-room/en/articles/735255-what-is-single-stream-technology) so you receive a single stream with all participants that is guaranteed to be the same for all users. However we provide an sfu mode as well for two participants and for sure if you handle local streams you can also work with those which we do not recommend to. Let me know if you need any further details.

Unfortunately I'm not sure what you mean by the first two steps but if you need any help on getting started let me know and I'll try to come up with an example.

Best wishes!

**Comment by Louiesmithsts** [comment]
Hi Christoph,

What I am asking is, Can the API provide me the video streams from the room? if so how can I pull that request/ what endpoint is that?

Also, can we speak on email?

Kind Regards

**Comment by unused** [comment]
The service is heavily based on WebRTC (using websockets and SIP), you can easily follow the network traffic using the default GUI to see the steps necessary to send and receive streams. If you need any additional support I'd suggest to contact sales@eyeson.com. Best wishes!
