### ISSUE TITLE
How to disable/not to display the add/invite guest using Eyeson API.

### ISSUE THREAD

**Issue by vkeenala** [eyeson-team/api#53]
![image](https://user-images.githubusercontent.com/58173189/84869875-393e6a80-b09c-11ea-86ad-a10389508432.png)

We want to disable invitees from adding guests and removing the lock meeting option. Is there an option to configure this behavior?

**Comment by unused** [comment]
Please use the configuration option `guest_token_available`.

```sh
curl -v -X POST \
  -H "Authorization: $(API_KEY)" \
  -d "user[name]=Bob" \
  -d "options[guest_token_available]=false" \
  "https://api.test-visocon.com/rooms"
```

**Comment by vkeenala** [comment]
Thank you.
