### ISSUE TITLE
We want to removing the lock meeting option. Is there an option to configure this behavior?

### ISSUE THREAD

**Issue by vkeenala** [eyeson-team/api#54]
![image](https://user-images.githubusercontent.com/58173189/84870635-2d06dd00-b09d-11ea-9501-074de4e8f038.png)

What is the purpose of Lock meeting room feature?

Please help on how to lock/unlock the meeting room for the user using Eyeson API.

**Comment by unused** [comment]
Lock meeting is a quite new feature, you can [find some details on our blog](https://www.eyeson.com/blog/new-features-alert-lock-meeting-and-end-meeting-for-all/). We will update the API and default web GUI with configurations to disable it soon.

**Comment by vkeenala** [comment]
Thank you.

**Comment by unused** [comment]
You can now use `options[lock_available]` and `options[kick_available]` to deactivate the features when joining a meeting.

```sh
curl -X POST \
  -H "Authorization: $(EYESON_API_KEY)" \
  -d "user[name]=Bob" \
  -d "options[lock_available]=false" \
  -d "options[kick_available]=false" \
  -d "options[exit_url]=https://eyeson.com/developers" \
  "https://api.eyeson.team/rooms"
```
