### ISSUE TITLE
Screenshot of just one source

### ISSUE THREAD

**Issue by gmandalaeveris** [eyeson-team/api#56]
Hi guys, we are using eyeson and we have a doubt (so it's not a real issue). Is it possible to take a screenshot of just one source? I mean, not the entire session but just one webcam image. We need to implement a scenario in which an agent needs to take a screenshot of a document without other people. Can we do it?

Thanks
Gabriele

**Comment by gmandalaeveris** [comment]
Hi Guys, we are proceding with standalone screenshot functionality in our application. Is it possible to disable snapshot via api?

**Comment by unused** [comment]
Hi there! There are several ways to create an image from streams, a client side-approach may come in handy for you, e.g. run the stream through a canvas and extract an image any time. We do not provide a configuration to disable snapshots at the moment.  Let me know if you need any further details.
