### ISSUE TITLE
Cannot see all the Eyeson meeting room features in mobile view

### ISSUE THREAD

**Issue by indrachith** [eyeson-team/api#57]
![1AC68545-5D7D-4537-81FE-CA5A28AA4B00-1](https://user-images.githubusercontent.com/56821169/85941197-0a977e00-b93f-11ea-96cf-2c800e1d89bc.jpg)

**Note:**

We cannot use the recording and other features in the mobile view.  

Also While click on exit option It is asking a confirmation pop up as 'End for all' and 'Leave meeting'. But in the mobile view, we cannot see that confirmation dialog box as below.

![image](https://user-images.githubusercontent.com/56821169/85941355-120b5700-b940-11ea-81a0-9e878e1a44de.png)

Please refer to the attached screenshot and help with this...

**Comment by unused** [comment]
Hi! We do provide a limited interface for mobile devices with the eyeson web UI. If you need specific features for your users you can easily build your own custom web interface. Please have a look at the [JavaScript package documentation](https://github.com/eyeson-team/js-docs) that provides you with many helpers and utilities, as well as at the [GUI example using react](https://github.com/eyeson-team/react-web-gui-example).
