### ISSUE TITLE
EyesOn API meeting room max number of participants

### ISSUE THREAD

**Issue by sergiu-sbp** [eyeson-team/api#58]
Hello,

We've reviewed the API documentation, however we were not able to find any reference to the max number of participants that we can add to a meeting room through the API. Is there a limit in this direction?

Thank you in advance,
Sergiu

**Comment by unused** [comment]
Hi there! We do not have a strict limit on the number of participants, however there are [no more than 9 participants shown in the single stream and up to 100 participants connected via audio](https://help.eyeson.team/eyeson-room/en/articles/925223-how-many-participants-can-join-a-room). We do recommend to [broadcast](https://help.eyeson.team/eyeson-room/en/articles/3902089-live-streaming-with-eyeson) your meeting if you have a larger group of viewers. You can find the RTMP handling in the [broadcast section of the api documentation](https://eyeson-team.github.io/api/api-reference/#broadcast). Do not hesitate to leave a comment if you have any further questions.

Best wishes!
