### ISSUE TITLE
I need a function for the meeting duration

### ISSUE THREAD

**Issue by mayerpeter** [eyeson-team/api#6]
in my use case the meetings are prescheduled with 20 minutes or 40 minutes on my platform. I need to show a countdown on the UI and I need a function to get the duration of the meeting after the meeting has ended. For business reasons I need to get the exact duration of the meeting from eyeson directly.

**Comment by unused** [comment]
You can receive information about a meeting by [registering a webhook](https://eyeson-team.github.io/api/api-reference/#register-webhooks) on room_instance_update. The starting date is provided in UTC in attribute `started_at`. You'll also receive an update when the meeting has ended with attribute `ended_at`, also in UTC. 

A easy way to show a current meeting time is to send an transparent image showing the current time every minute using the [data layers](https://eyeson-team.github.io/api/api-reference/#content-integration-aka-layers).
