### ISSUE TITLE
Different webhook target URL for different environments

### ISSUE THREAD

**Issue by gsinghab2** [eyeson-team/api#60]
Hi,

We have dev, qa and prod environment and would like to configure different webhook target URL for each environment. The problem is we are using same API key for each environment. Is there a sandbox environment that we can use for non prod environment with different API key? If not, is there a way  to test webhooks in non prod environments?

Thanks,
-Gautam

**Comment by unused** [comment]
We do not provide different environments and webhooks, if you require such you might have to create a proxy for such.

**Comment by gsinghab2** [comment]
@unused Is there a way to annotate a meeting w.r.t to environment?  If not, how do you suggest we should proxy the webhook to appropriate environment?

**Comment by unused** [comment]
If you [join a meeting](https://eyeson-team.github.io/api/api-reference/#eyeson-room) you either set your own room identifier or receive one generated by the eyeson API service.
