### ISSUE TITLE
"error": "Invalid access key"

### ISSUE THREAD

**Issue by sasidhar3** [eyeson-team/api#70]
I am trying eyeson APIs to integrate with my application. I created the room with API Key and trying to access the room with
the access key [ which i got in the response of creating room( POST /rooms) ], But every time i am getting response as Invalid access Key, can you please explain the possible solution for this. We are hoping to build business partnership with you, for that we are checking whether eyes on video conferencing will reach our expectations or not.
It would be great if you share sample HTML request and response format , looking forward for your reply.

**Comment by unused** [comment]
A common mistake is not to join a meeting after it has been created, this will expire the access token after a short period of time. You only have to communicate to the API service as soon as your user wants to join a meeting, then redirect on-the-fly to the provided eyeson web GUI or to use the access token in your own user interface. If that does not resolve your issue please do not hesitate to leave a comment!

**Comment by sasidhar3** [comment]
Hi
Thanks for the reply, I tried in all possible methods and i am still getting the same error. can you please explain in detail on room creation and accessing APIs ( NOTE : i read all your API documentation pages and its not clear enough to build the application )
below is the POST call i am making
![Creating_Room](https://user-images.githubusercontent.com/67953755/88764102-fd65ed00-d191-11ea-8999-1e96c8bf3264.png)
below is the GET call i am making to get user details
![Getting_Usr_Info](https://user-images.githubusercontent.com/67953755/88764133-0e166300-d192-11ea-857f-ffb8dc65f350.png)
Every time i am getting invalid access key. can you please give a solution to this problem.

Apart from that, we want to access your snapshots to our application to do real time facial recognition. can you please provide API to access snap shots from the meeting ?

**Comment by unused** [comment]
You have some extra `:` in your URL (2nd screenshot) that breaks the endpoint - try https://api.eyeson.team/rooms/Kra5...wgeE/users/12345 ... next time - You can also check the network requests in the web GUI to get an idea of the requests required, the user identifier should also be the one received via API responses not the custom identifier which only purpose is to keep your participants unique.

For facial recognition I'd suggest to use a client side canvas to handle temporary images as snapshots might not be the correct match as they are handled persistent. Let me know if you have any other questions!
