### ISSUE TITLE
Accessing the recordings

### ISSUE THREAD

**Issue by BindujaDas** [eyeson-team/api#71]
Hi @unused ,
                      I'm trying use the api's provided in the document.I'm successfully able get the access key and create and join the meeting. I'm trying to record the meeting and access it after the call ends using same access key as described in the doc but unfortunately i'm not able to access and download it. It'd helpful if could just tell me the exact format that i should be framing the request and if there's anything that i need to change.

Thanks.

**Comment by unused** [comment]
Ahoi! Thanks for the feedback, we recommend to handle recordings server-side and use [webhooks](https://eyeson-team.github.io/api/api-reference/#register-webhooks) for this purpose. Best wishes!
