### ISSUE TITLE
Let room expire after 24h

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/api#72]
We consider intentionally letting a room expire 24h after creation. I tried to find it in the documentation but didn't find something like that. Being able to manually close a room would also be a good start but didn't find it in the documentation. yes user tokens that expire in a controlled way would also solve this problem if this is possible.

Any help very much appreciated!

**Comment by unused** [comment]
There is no need to create any room in the eyeson API service upfront but *join* a meeting on-demand. If you want to manage rooms, you can do this in your application in any way. When a participants joins a room you request a room session and retrieve an  unique access token that will expire after a very short period of time.

You can end a meeting [using the HTTP DELETE method](https://eyeson-team.github.io/api/api-reference/#eyeson-room) for any running meeting.

Please do not hesitate to leave a comment if you have any further questions.
