### ISSUE TITLE
Is there any way that I can get the PDF file name that I want to share?

### ISSUE THREAD

**Issue by FredGuo-CN** [eyeson-team/api#73]
Greetings, Eyeson team,

I am evaluating that if eyeson is the proper solution to integrate with my application. 

My need is that I want to highlight the specific page of the PDF file in the preview of sidebar when I am sharing it through the web conference. The specific page of the PDF is returned by another application based on real-time processing. So I would like to add another layout on the PDF preview UI,  however, if I want to use the existing feature of the PDF sharing of eyeson, I can not touch the PDF and I even don't know the name of the PDF that selected. Any way?

BTW, is there also a way to get the real-time audio stream of a room?

**Comment by unused** [comment]
Hi, nice to meet you! In case you need to adapt the document to present or pre-process/analyze the audio stream we'd recommend to build a custom user interface. We [provide some helpers to start with](https://eyeson-team.github.io/js-docs/). Additionally a custom user interface can integrated seamlessly into any other web app. If you have any further questions please do not hesitate to leave a comment or create a new issue. Best wishes!
