### ISSUE TITLE
PDF sharing and other features available in JS-doc?

### ISSUE THREAD

**Issue by FredGuo-CN** [eyeson-team/api#74]
Hi eyeson,

Thanks, my previous question was anwsered and I was recommneded to use the eyeson JS lib to implement my needs. One curious question that is if there is opensource for the eyeson UI features because my needs is pretty close to the existing eyeson UI and I want to leverage that.

**Comment by FredGuo-CN** [comment]
And I didn't see any canvas converting function in the JS-doc, which means that I have to implemente the PDF and other layout overlay for my own?

**Comment by unused** [comment]
We do not provide the default web UI sources nor do we have current plans to open-source it but I'm happy to forward your request internally. However dealing with PDF is pretty easy, I'd recommend to use [pdf.js](https://github.com/mozilla/pdf.js) to handle your documents and simply [capture the stream](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) from the resulting canvas. The eyeson API service will for sure accept any valid media stream and broadcast it to other participants. Have a look on the [layout section](https://eyeson-team.github.io/api/api-reference/#layout) if you want the document fill the entire video podium. If you have any further questions on this or need any help do not hesitate to leave a comment. Best wishes!
