### ISSUE TITLE
Rooms created through API not visible in dashboard

### ISSUE THREAD

**Issue by tomdebuyser** [eyeson-team/api#75]
I am exploring the functionalities om eyeson by using the API. If I login to the dashboard I can see one room called "eyeson" and I can also check the history of this room. However, if I create a room with the API, I do not see it appear in the dashboard, neither see anything in the history.

Is this normal behaviour? Or is it due to my trial account? Or is there no overview of all "activity" for API created rooms?

Thanks for your answer.

**Comment by unused** [comment]
The platform and the API are standalone products and work independently from each other. You can use the API to build your own video conferencing solution. The [accounts.eyeson.team](https://accounts.eyeson.team) platform is an eyeson product that by itself uses the API as service. If you have any further questions on this do not hesitate to leave a comment! Best wishes!

**Comment by Pabbly** [comment]
means Room created via API not show in Eyeson Dashboard

**Comment by unused** [comment]
> The platform and the API are standalone products

**Comment by Pabbly** [comment]
means Room created via API not show in Eyeson Dashboard

**Comment by unused** [comment]
The eyeson API is the core of eyeson video conferences and you can use it to build your own product on top of it. Your application can integrate a modern single-stream based video solution with lots of features. The software platform at [accounts.eyeson.team](https://accounts.eyeson.team/) which I expect you refer to as "Eyeson Dashboard" is a standalone product, not connected to your API project and for sure will not reflect any rooms or meeting history.
