### ISSUE TITLE
500 Internal Server Error when creating rooms with eyeson API

### ISSUE THREAD

**Issue by codebarz** [eyeson-team/api#76]
Hello,

I get a `500` internal server error when i try creating rooms with the eyeson API so i can get the link to share for video confrence .

I am sending a `POST` request to `https://api.eyeson.team/rooms` with `Authorization: {{API KEY}}` as header and also a body `{"user": "username"}` but when i send this request, i get an internal server error.

What is the solution to this?

**Comment by unused** [comment]
Hi! Please use POST parameters rather than an JSON encoded body and ensure you are using the proper attribute names. The examples from the API should give you some idea on how to do this in your environment at hand.

```
$ curl -X POST \
  -H "Authorization: YOUR_API_KEY" \
  -d "user[name]=Bob" \
  "https://api.eyeson.team/rooms"
```
