### ISSUE TITLE
Scheduling the creation of a room

### ISSUE THREAD

**Issue by tomdebuyser** [eyeson-team/api#77]
My application has the ability to schedule appointments with other users of the application. As with google meet, I want to attach the eyeson room link to the appointment immediately. Unfortunately, I read that by default only 25 rooms could exist in parallel. Is this restriction based on _active_ rooms only? Or is there another solution for my use case?

**Comment by unused** [comment]
The best solution for your use case is *not* send any request to the eyeson API service as long as you do not want to join a meeting. There is no need to create a room upfront and it will expire after a short period of time if no one joins. This however gives you the opportunity to have full control over the scheduling and expiration process on your side. Simply setup a simple endpoint your invitation links point to that handles your users to join and request a meeting as soon as you decide a participant is ready to join. Hope that helps, if you have any further questions on this please do not hesitate to leave a comment!
