### ISSUE TITLE
Download recordings?

### ISSUE THREAD

**Issue by mikkopalo** [eyeson-team/api#79]
Hi!

[API documentation](https://eyeson-team.github.io/api/api-reference/#recording) mentions that it's possible to download recordings by using direct download URLs.

By using webhooks, I got following output:
```
{
    "api_key": "MY_PRIVATE_APIKEY",
    "type": "recording_update",
    "recording": {
        "id": "HIDDEN_ID",
        "created_at": 1599166126,
        "duration": 49,
        "links": {
            "self": "https://api.eyeson.team/recordings/HIDDEN_ID",
            "download": "https://s3.eyeson.com/meetings/ACCESS_KEY_I_THINK/HIDDEN_ID?X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Credential=AH07FBAZO9IYS38J6742%2F20200903%2Fus-east-1%2Fs3%2Faws4_request\u0026X-Amz-Date=20200903T204939Z\u0026X-Amz-Expires=3600\u0026X-Amz-SignedHeaders=host\u0026X-Amz-Signature=be0fc58b9004ab55c66b29a63652fa3f4e3d1793a0d0e619a1e5b951b6a7857d"
        },
    }
}
```

So, when I try to download using "download" link by using curl:
`curl "https://s3.eyeson.com/meetings/ACCESS_KEY_I_THINK/HIDDEN_ID?X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Credential=AH07FBAZO9IYS38J6742%2F20200903%2Fus-east-1%2Fs3%2Faws4_request\u0026X-Amz-Date=20200903T204939Z\u0026X-Amz-Expires=3600\u0026X-Amz-SignedHeaders=host\u0026X-Amz-Signature=be0fc58b9004ab55c66b29a63652fa3f4e3d1793a0d0e619a1e5b951b6a7857d"`
It then says: "Access Authorization failed.".

Then I added the API key:
`curl -H "Authorization: MY_PRIVATE_APIKEY" "https://s3.eyeson.com/meetings/ACCESS_KEY_I_THINK/HIDDEN_ID?X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Credential=AH07FBAZO9IYS38J6742%2F20200903%2Fus-east-1%2Fs3%2Faws4_request\u0026X-Amz-Date=20200903T204939Z\u0026X-Amz-Expires=3600\u0026X-Amz-SignedHeaders=host\u0026X-Amz-Signature=be0fc58b9004ab55c66b29a63652fa3f4e3d1793a0d0e619a1e5b951b6a7857d"`
It then says: "AWS authentication requires a valid Date or x-amz-date header."

Then I tried to add additional -H "Date: Thu, 03 Sep 2020 20:49:39 GMT" or -H "x-amz-date: Thu, 03 Sep 2020 20:49:39 GMT" headers to curl, it just says "Access Authorization failed." I suppose, that date format should be as RFC 7231 defines?

What am I doing wrong?

**Comment by unused** [comment]
You only need the API key to receive the recording (JSON) response, the download url works fine but will expire after some time so ensure to access the file soon after requesting it. Please also ensure the download link is not changed when trying to download it (e.g. output for copy & paste to curl is not escaped!). Let me know if this solved your issue.

**Comment by mikkopalo** [comment]
Thanks for clarification.

After fiddling with different things, I found the root cause of this problem: I didn't decode JSON data properly, so the download link wasn't in right format (eg. convert \u0026 code to & character).

Have a nice weekend! :)
