### ISSUE TITLE
Presentation & video

### ISSUE THREAD

**Issue by ragheeddamaj** [eyeson-team/api#80]
Dear,

I noticed that the video stream is closed when I do a presentation... why? this is a weird point that my customer complaint about!

Regards,

**Comment by unused** [comment]
Hi there! Can you please add some details to your issue as I cannot figure out the problem from your short description. Maybe a screenshot might be helpful as well. Thank you in advance!

**Comment by ragheeddamaj** [comment]
Hi & Thx for your support

As attached, whenever i present my screen, the video (camera) closes (I am not able to present my screen & share my video camera at the same time)

Please check out the attached screenshot

![SVideoharedScreenshot](https://user-images.githubusercontent.com/22028182/93438455-017ed300-f8d6-11ea-918e-f51eb49658da.jpg)

**Comment by ragheeddamaj** [comment]
Please this is a kind reminder!

**Comment by unused** [comment]
Thank you for the screenshot. We currently do not provide an option like this. If you need to show a video of the person (or other participants) inside the screen captured stream you have to merge it on client side and provide it to the server, similar to the file presentation feature. If you need further details on how to build your own custom user interface please have a look on the [documentation that covers the helpers we provide](https://eyeson-team.github.io/js-docs/) as well as on the short [example using React](https://github.com/eyeson-team/react-web-gui-example/).
