### ISSUE TITLE
Meeting link expiry

### ISSUE THREAD

**Issue by onubrooks** [eyeson-team/api#81]
Hi,
Following the getting started guide, I made a call to the rooms endpoint and got the correct response as expected. However, on visiting the links.gui key of the JSON response, I get a message saying the link has expired.
![eyeson](https://user-images.githubusercontent.com/26160845/93766157-e7aefa00-fc0d-11ea-9860-c992fc6e2e2a.PNG)

Here's a sample of the JSON response:
`{
    "access_key": "...",
    "ready": false,
    "locked": false,
    "room": {
        "id": "...",
        "name": "...",
        "ready": false,
        "started_at": "2020-09-21T11:39:52.076Z",
        "shutdown": false,
        "sip": {
            "uri": "@",
            "domain": null,
            "authorizationUser": null
        },
        "guest_token": "..."
    },
    "team": {
        "name": "Onuh Abah"
    },
    "user": {
        "id": "1",
        "name": "dr who",
        "avatar": null,
        "guest": false,
        "blocked": false,
        "ready": false,
        "sip": {
            "uri": "@",
            "domain": null,
            "wsServers": "wss://sipcore-1.visocon.com:443",
            "instanceId": "b3df2d7a-a223-1aaf-beef-2717693596c8",
            "userAgentString": "visocon/webrtc",
            "authorizationUser": null,
            "displayName": "64722077686f",
            "stunServers": [
                "stun:nuts.eyeson.com:3478"
            ],
            "turnServers": [
                {
                    "urls": [
                        "turn:nuts.eyeson.com:3478",
                        "turn:nuts.eyeson.com:3478?transport=tcp",
                        "turns:nuts.eyeson.com:443?transport=tcp"
                    ],
                    "username": "...",
                    "password": "..."
                }
            ],
            "registerExpires": 60,
            "password": "..."
        }
    },
    "links": {
        "self": "https://api.eyeson.team/rooms/...",
        "gui": "https://app.eyeson.team/?...",
        "guest_join": "https://app.eyeson.team/?guest=...",
        "websocket": "https://api.eyeson.team/rt?access_key=..."
    },
    "options": {
        "show_names": true,
        "show_label": true,
        "exit_url": null,
        "recording_available": true,
        "broadcast_available": true,
        "layout_available": true,
        "reaction_available": true,
        "suggest_guest_names": true,
        "lock_available": false,
        "kick_available": true,
        "sfu_mode": "ptp",
        "layout_users": null,
        "custom_fields": {}
    },
    "presentation": null,
    "broadcasts": [],
    "recording": null,
    "snapshots": []
}`

**Comment by unused** [comment]
Hi there, nice to meet you :) The meeting link will expire after a short period of time if no one joins the meeting. Therefor we recommend to **only** request to join a meeting when your user is ready and directly redirect them to the web GUI provided. If you need a link to invite your participants but do not want to start a meeting yet you do not have to communicate with the eyeson API but can handle this (invitation, scheduling, authentication, etc.) in your application and join a meeting with your user on-the-fly. I hope this answers your question. Please do not hesitate to leave a comment if you need any further help. Best wishes!
