### ISSUE TITLE
SIP registration

### ISSUE THREAD

**Issue by nav-andrea** [eyeson-team/api#82]
Hello, we're trying to use the SIP information on the https://api.eyeson.team/rooms/<roomid> answer to register an Asterisk PBX on the conference 
In this json we can find information about SIP-URI and password, stun server, turn server
We create the following registration on Asterisk

[eyeson]
type=peer
username=<authorizationUser>
fromuser=<authorizationUser>
secret=<password>
host=integrations.visocon.com
insecure=port,invite
dtmfmode=rfc2833
transport=tls
port=443

As you've indicated to use TLS 443 port, we've tried also with 5061 port
We receive a timeout error and the registration failed
We've tried also with a softphone but we've the same error 

Could you show us a correct registration string with a PBX or softphone?

Thanks

**Comment by unused** [comment]
Hi there, nice to meet you! If you setup your own dial-in functionality you'll have to handle PSTN-SIP gateway by your own and connect to our SIP infrastructure. Note that the credentials received are per meeting and user, so please ensure you fetch proper ones upfront. The host should be one of the sip domains (e.g. sipcore-0.visocon.com, see wsServers in response and strip the protocol) and the users follow the pattern "<ssss>@integrations.visocon.com", but you must not resolve integrations.visocon.com. The connection must work with TLS-443. From the asterisk docs it seems that it should look something like:

```
username=1234
host=sipcore-0.visocon.com
fromuser=1234
fromdomain=integrations.visocon.com
transport=tls
port=443
```

Good luck and best wishes!

**Comment by nav-andrea** [comment]
Hello, it's ok using the host indicated by you
Now we receive a registration error
This is our SIP block, what does we've to use in the username and fromuser variables?

 "sip": {
            "uri": "--authUser--@integrations.visocon.com",
            "domain": "integrations.visocon.com",
            "wsServers": "wss://sipcore-1.visocon.com:443",
            "instanceId": "--instance-id--",
            "userAgentString": "visocon/webrtc",
            "authorizationUser": "--authUser--",
            "displayName": "--displayName--",
            "stunServers": [
                "stun:nuts.eyeson.com:3478"
            ],
            "turnServers": [
                {
                    "urls": [
                        "turn:nuts.eyeson.com:3478",
                        "turn:nuts.eyeson.com:3478?transport=tcp",
                        "turns:nuts.eyeson.com:443?transport=tcp"
                    ],
                    "username": "--code--:--authUser--",
                    "password": "--password--"
                }
            ],
            "registerExpires": 60,
            "password": "--veryLongPassword--"
        }

**Comment by unused** [comment]
The `username`, `fromuser` value can be taken from `authorizationUser`.

**Comment by nav-andrea** [comment]
Great, using these parameters we get connected
What uri we've to call to instradate the SIP call to the conference?

We've tried with several parameters, such as the URI starting with "conf_" as
"uri": "conf_5f6b35b521310f0011daacda@integrations.visocon.com"
and I receive a Forbidden message

Instead using other parameters (access_key, guest id, ...) I recevie a Not Found error

**Comment by unused** [comment]
The `uri` is right, please double check that your are not already connected with this user. We expect the forbidden you received caused by the user already participating or the user not being registered to this meeting at all.

You can check the ongoing communication by using the default web GUI on any meeting and checking the sent/received messages, e.g. using Chrome browser developer tools network tab, select `sipcore-x.visocon.com`, browse the messages.

**Comment by nav-andrea** [comment]
You are correct, I was connected with the webrtc interface
Thanks a lots
