### ISSUE TITLE
Display only room owner

### ISSUE THREAD

**Issue by codebarz** [eyeson-team/api#83]
I have been able to set up a room and allow users to join the room using the eyeson npm package.

But there is one thing I need to achieve. Instead of splitting the room screen to show all users in the room, I want to display only the room owner (sort of like a single user Instagram live thing). Is there an option to set to do this? Because I can't seem to successfully find any in the eyeson doc.

Thanks

**Comment by unused** [comment]
You can use the [layout feature](https://eyeson-team.github.io/api/api-reference/#layout) to show a single participant only. However if you want to [broadcast](https://eyeson-team.github.io/api/api-reference/#broadcast) only one stream to many users you should definitely stick to [RTMP](https://www.eyeson.com/blog/eyeson-live-streaming-via-rtmp/) and avoid joining the viewers to the meeting. Please do not hesitate to leave a comment if you have any further questions on this!

**Comment by codebarz** [comment]
Quick question @unused , is this the right way for setting layout https://api.eyeson.team/rooms/ACCESS_KEY/layout?users[]=${user.id}` such that the user id is the id of owner of the room?

And also, the video calls just shows a dark blank screen on ios devices.Is this a general issue with the eyeson API or is there a configuration i need to set while creating a room

**Comment by unused** [comment]
Yes, the request is fine but it has to be a POST request and it's best to start your meetings with `options[sfu_mode]=disabled` to ensure layout is also available when there are only two users in a meeting. I put together an example using `curl` for you:

```sh
$ curl -X POST -H "Authorization: <API_KEY>" -d "user[name]=demo" \
       -d "options[sfu_mode]=disabled" "https://api.eyeson.team/rooms"
# immediately join the meeting using the link in `links.gui` or the meeting will expire. Copy the values
# of `access_key` and the `user.id`. Note: No need to use the api key here as the user authorizes and
# authenticates using the access key.
$ curl -X POST -d "users[]=<user.id>" "https://api.eyeson.team/rooms/<access_key>/layout"
```

Regarding the iOS issue: There is some extra work you have to do [when using autoplay as Safari has some restrictions](https://webrtchacks.com/autoplay-restrictions-and-webrtc/) on this. Adding `autoplay` and `playsInline` on your HTML video tag should fix it.
