### ISSUE TITLE
host and guest differentiation

### ISSUE THREAD

**Issue by priyankapalkar** [eyeson-team/api#84]
1. We have created free account on eyeson for api access. We have created room using api only and recorded one of session to test. we have followed your api https://eyeson-team.github.io/api/api-reference/#recording but not getting any response.

2. As per the docs https://eyeson-team.github.io/api/api-reference/#user-and-guest-user. you have provided to for create guest user. we are getting the response too but when we access the guest_join url it is asking for guest user name although we have passed name parameter to the api.

3. we have followed your boadcaste api https://eyeson-team.github.io/api/api-reference/#broadcast. we have passed
the mentioned stream_url and platform too but we are getting following response -  "error": "Failed to create Broadcast, check stream url or retry". 

Our main requirement is 1 host should be created and many guest.

Looking forward to hearing from you.

**Comment by unused** [comment]
Hi there, recordings have to be processed async so you have to set up a webhook - only one! - to receive them. For the broadcast you should use the platform `generic` for any target. Please provide further details if that does not work for you. User and guest users do not have any difference, however if you know the name of the participant to join simply join the user: use a room identifier so participants end up in the same meeting. The guest token received however can be used to join users within a running meeting but without the need for authentication (aka using your api-key). This is convenient if you have a client-side application that runs your meeting but is not authenticated with your application services. In case you need to handle certain permissions you can easily build a custom UI and proxy control through your application. With this approach one can simply setup any user/role management with no restrictions from eyeson. Please let me know if you need any further details. Best wishes!
