### ISSUE TITLE
Want to remove some options.

### ISSUE THREAD

**Issue by priyankapalkar** [eyeson-team/api#85]
We are using eyeson api to create room. We want to disable some options from the window.
1. Device Setting.
2. Quick Join.
3. Dark Mode.
4. Full Screen.
5. Help.

How can we disable that options.

**Comment by unused** [comment]
Thank you for the feedback. Please note that we do allow [some options](https://eyeson-team.github.io/api/api-reference/#eyeson-room) to configure the web GUI provided by eyeson. You can disable "Quick Join" by using the `options[guest_token_available]` configuration. We currently have no plans to extend the current options but I'm happy to keep your request in our backlog.
However if you need a specific behavior, look and feel and fixed set of features we recommend to build a custom UI. A set of helpers to do so is provided with the [eyeson JavaScript package](https://eyeson-team.github.io/js-docs/). Please do not hesitate to leave a comment if you have any further questions on this. Best wishes!
