### ISSUE TITLE
webhook related query

### ISSUE THREAD

**Issue by priyankapalkar** [eyeson-team/api#86]
1. we have register room_update webhook using following documentation https://eyeson-team.github.io/api/api-reference/#register-webhooks but we are not getting any response. can you provide us sample code for webhook.
2. Also, as per our requirement we don't want to show logo at the time of loading. Is there any way to hide or remove that logo.
3. can we change the color codes.

**Comment by unused** [comment]
Please ensure that your endpoint is public available and listening for a POST request. You can check the last sent timestamp and status code received using the `/webhooks` (GET) endpoint.
We do provide some options to adapt the default web gui. Currently there are no configurations for loading animations and colours. However you can easily build your own user interface, we provide some [helpers](https://github.com/eyeson-team/js-docs) and some [examples](https://github.com/eyeson-team/react-web-gui-example). Best wishes!
