### ISSUE TITLE
Not able to get webhooks response

### ISSUE THREAD

**Issue by priyankapalkar** [eyeson-team/api#88]
I have created a code/script that lets me create room and just after that i have posted types(room_update) to webhook with a target URL.

But in my target URL i am only able to get the status reponse code as 200 and last sent timestamp and not anything regarding room creation.

Please help me with this issue.

**Comment by unused** [comment]
Please only create **a single** webhook, only the last one created will be used and ensure your receiving service accepts a HTTP POST request. The room details are sent as JSON encoded body, you can check last timestamp of the webhook and status code received using the `/webhooks` [GET endpoint](https://eyeson-team.github.io/api/api-reference/#register-webhooks). Do not hestitate to leave a comment if you need any further help. Best wishes!
