### ISSUE TITLE
remove quick join option

### ISSUE THREAD

**Issue by priyankapalkar** [eyeson-team/api#89]
we are using eyeson api for creating room. we are able to create room and we want guest to be join the room.we want to hide quick join and invite guest option from UI. Guest able to join the room using the guest_join url only. Please help us with this.

**Comment by unused** [comment]
Please use option `options[guest_token_available]` [to disable the guest token](https://eyeson-team.github.io/api/api-reference/#eyeson-room) (and hide the quick join button). The guest join URL is only required when joining users from within a client application. Simply join users via API in your application, use the same room identifier (`id`) so users end up in the same meeting. Best wishes!
