### ISSUE TITLE
Unable to add layers to a video call

### ISSUE THREAD

**Issue by bwoolnough** [eyeson-team/api#9]
I am trying get layers working in a video call but have not been able to do so.

I don't know if it makes a difference, but my API key is linked to a free licence.

After creating a room I have tried making post requests like the following:

`https://api.eyeson.team/rooms/<access_key>/layers?insert[icon]=<image_url>&insert[title]=<title>&insert[content]=<content>&z-index=1`
and
`https://api.eyeson.team/rooms/<access_key>/layers?url=<image_url>`

The response status I get is 201 so it seems to be successful, however I do not see the layers in the conference video. I have tried several (png) images and none have worked.

I'm not sure if it's the URL or the images I've tried, or if I'm missing something.

**Comment by bwoolnough** [comment]
This has been resolved. Because I was alone in the call, it was running in SFU mode meaning layers were not shown.

Forcing MCU mode by adding the options[sfu_mode] parameter allows you to see layers - see https://eyeson-team.github.io/api/api-reference/#eyeson-room. As does including 3 or more people in a call.

**Comment by unused** [comment]
Thank you for reaching out, I guess you are in [SFU](https://webrtcglossary.com/sfu/) mode which does not reflect the layers, as individual streams are transported. For a quick check, simply add to guests to the meeting - so three participants are present - then you should see the images send. The examples you provided look correct, however please ensure to use HTTP method POST `curl -XPOST --form "url=https://.../filename.png" "https://api.eyeson.team/rooms/<access_key>/layers"`. To disable the SFU mode and ensure to see the images also in ptp and single, simply provide `options[sfu_mode]=disabled` within room configuration.

Please do not hesitate to leave a comment if it did not resolve your issue. It seems this is not very clear from the documentation, I'll extend it by additional information on this topic asap.
