### ISSUE TITLE
Recordings can not be stopped by guest.

### ISSUE THREAD

**Issue by priyankapalkar** [eyeson-team/api#90]
we are able to record the room but we don't want to give recording stop permission to all participants. recording should get stop when we end the meeting for all. can you help with this. 

Note : we are using eyeson api for room creation.

**Comment by unused** [comment]
We do not handle any user roles in the eyeson default web interface, however you can easily build your own to do so. We do provide [helpers and utilities](https://github.com/eyeson-team/js-docs) as well as [examples](https://github.com/eyeson-team/react-web-gui-example) on how to get started.
