### ISSUE TITLE
Custom Web UI

### ISSUE THREAD

**Issue by priyankapalkar** [eyeson-team/api#91]
We are trying to create our own Web user interface for video conferencing. Can you please help us with some example and documentation for how we can create own UI and implement eyeson video conferencing. Thank you...:)

**Comment by unused** [comment]
We recommend to use the [eyeson JavaScript package](https://www.npmjs.com/package/eyeson) ([documentation](https://eyeson-team.github.io/js-docs/)) as it provides a simple way to connect and offers some helpers that make things like device management pretty easy.

You can find [an example using React hosted on GitHub](https://github.com/eyeson-team/react-web-gui-example) that has some basic features like audio/video mute and screenshare. Please do not hesitate to create another issue or leave a comment if you have any further questions! Best wishes!
