### ISSUE TITLE
Webhook callback is not working

### ISSUE THREAD

**Issue by gsinghab2** [eyeson-team/api#92]
We are registering the callback URL but when we stop recording we are not receiving any callbacks. Can you please look into it?

**Comment by gsinghab2** [comment]
It was working before and stopped working all of sudden starting the mid of Oct.

**Comment by gsinghab2** [comment]
It seems like the callback is working but it is delayed by hours after the recording is stopped.

**Comment by unused** [comment]
Thank you for the feedback. The recording takes some time to post-process but it should not take up hours. We had some processing that took longer on Friday but I'd have expected hours of delay. Can you please confirm that you still see this behaviour?
