### ISSUE TITLE
Eyeson room opens EyesOn app but not the meeting

### ISSUE THREAD

**Issue by codingyourlife** [eyeson-team/api#93]
Steps to reproduce:

1. Install the EyesOn app
2. Open e.g. https://app.eyeson.team/?nrORMxCYEJ4mrRPJdYxRBY5U on mobile

-> The eyeson app opens but on the main page and it does not open the room.

It would be an improvement if the app does not open at all. Ideally of course it should open the correct room also in the app.

Please fix :)

**Comment by unused** [comment]
As mentioned in [the issue you created earlier](https://github.com/eyeson-team/react-web-gui-example/issues/18) please [visit our help center or contact our support team](https://help.eyeson.com/) if you find any issue. Unfortunately we cannot manage questions and issues here that do not concern the eyeson API service.
