### ISSUE TITLE
Eyeson UI bugs

### ISSUE THREAD

**Issue by romashauk** [eyeson-team/api#94]
1. The first bug appeared when making a custom layout and pressing the button to apply. 
It says that there is an error with the codename skyfall. Very strange, any ideas what does it mean? 
2. When starting recording the error appears. also, that gave an error.
3. In Assign a video position modal there is an error with the Russian translation. It says 'приминить' instead of 'применить'. Please fix it.
Thanks in advance

**Comment by opusonline** [comment]
Hello, thank you for your feedback!

Points 1 and 2 refer to the same issue and that is an error in the XHR request from UI to eyeson API (= error codename "Skyfall"). I have tested it and it worked well. So the question is, do you still get the error? If this happens again, we need more details from you. You can have a look in the browser console and search for "ComApi::handleError" or the Network panel XHR connections starting with "https://api.eyeson.team/…" to find out more information.

Regarding point 3, thank you for the heads-up! We will update this asap.

Please don't hesitate to leave a comment if you need any further help.

Best regards, Stefan

**Comment by romashauk** [comment]
Hello,
1,2  - I received the same error a few times. 
The problem is: 'The feature is not available for this room'
Our case:
We have two roles of participants join: 
- for one of them When joining the room I am sending the param layout available = false ( in order to hide that option into the menu)
- for the next part of the when joining the room, I am sending the param layout available = true
Could it be the problem ?

**Comment by opusonline** [comment]
Hello, thanks for update, now I know what happens.

You're right, the reason for the error is that you mix room settings per user, but that's not supported. The configuration is done at room level, you can't allow layout for specific users via API.

I suggest to hide layout for all users and just set a layout using the API. Same for recording.

In case you need roles, you have to create a custom UI and proxy control on demand.

Best regards, Stefan
