### ISSUE TITLE
choosing device

### ISSUE THREAD

**Issue by joaocolganenet** [eyeson-team/api#96]
Hi,

I need to be able to choose the device to use for the microphone and webcam, is it possible?

Thanks

**Comment by opusonline** [comment]
Hi,
choosing mic and cam is possible in the app GUI.
After starting a meeting you'll receive the link to the GUI. When you open this link you'll see a preview screen where you can select your preferred devices.
I hope that answers your question.
Please do not hesitate to open another issue or leave a comment if you have any further questions!
Best regards, Stefan

**Comment by joaocolganenet** [comment]
I'm sorry, maybe I didn't understand, i'm using your api to manage the videocall but in my custom GUI.
I'm using your calls in javascript (https://eyeson-team.github.io/js-docs)

i'm using this one: eyeson.default.start(...) but i don't understand how to change or choose a device

**Comment by unused** [comment]
You can use the [device manager](https://eyeson-team.github.io/js-docs/utilities/#device-manager) to handle them in your custom web UI. If you have any further questions on this do not hesitate to leave a comment.

**Comment by opusonline** [comment]
Thanks @unused!
Just a quick hint: 
- use DeviceManager to select devices
- when finished, use storeConstraints method
- after that, call eyeson.join(…) to start the meeting or call eyeson.send({ type: 'start_stream', … }) to update changes during a meeting
Best regards, Stefan

**Comment by joaocolganenet** [comment]
thanks for @unused  and @opusonline 

ok I tried and now I can see the devices. but I can't figure out how to tell eyeson to use a particular device.

I use this:
eyeson.default.send({
    type: 'change_stream',
    stream: ....
    video: true/false,
    audio: true/false
});

which parameter should I use (to change webcam/microphone and speaker)?
thanks

**Comment by opusonline** [comment]
@joaocolganenet 

Make sure to call `storeConstraints` method of your DeviceManager instance. And to actually use the changed devices, you need to restart the stream by using the `start_stream` event.

See https://eyeson-team.github.io/js-docs/events/#start_stream for more information.

**Comment by joaocolganenet** [comment]
I tried but i have some difficulties.

I used DeviceManager to get the device I want to use 
![image](https://user-images.githubusercontent.com/61703328/107392146-a99d6e80-6af9-11eb-9da2-841d123ae0c7.png)

Then I used this method deviceManager.setAudioOutput(parameter), first I tried to pass the whole object (InputDeviceInfo) as parameter,
then I called storeContraints and finally I called 
eyeson.default.send({  type: 'start_stream', video: true, audio: true });

but I got this message:
![image](https://user-images.githubusercontent.com/61703328/107393882-8d9acc80-6afb-11eb-875b-329ac8f06539.png)

so Instead of pass the whole object I tried with "deviceId"
no errors in console but then I saw this:

![image](https://user-images.githubusercontent.com/61703328/107394445-2fbab480-6afc-11eb-8422-512614adf3fb.png)

I tried also with the others attributes of InputDeviceInfo but I got the same error in console.

I don't understand what I'm doing wrong

**Comment by opusonline** [comment]
I think you're on the right track!

Please make sure to use setAudio**Input** instead of **Output**. `setAudioInput` and `setVideoInput` methods take only the deviceId as parameter.
After that, call `storeContraints` and send the `start_stream` event as you did.

I suggest to try open your app in a new incognito window to get a fresh system device permission dialog and a clean browser setup.

Best wishes!

**Comment by joaocolganenet** [comment]
thanks again @opusonline 

if I use setVideoInput for the camera I get this message:
![image](https://user-images.githubusercontent.com/61703328/107488221-5b36b100-6b87-11eb-9dc2-a4b24232992d.png)

I tried to use change_stream instead of start_stream but i got the same message.
I noticed that if I turn off and then turn on with change_stream, it works, but It doesn't seem the right way to make it work.

If I don't use eyeson.default.send after storeContraints, I still get an error message:
![image](https://user-images.githubusercontent.com/61703328/107488826-30009180-6b88-11eb-94be-8609653ca4b8.png)

thanks

**Comment by opusonline** [comment]
Ok, this is a general issue with WebRTC in your browser.
A quick Google search showed this bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1128913
Let me know if this solves your issue.
Best wishes!

**Comment by joaocolganenet** [comment]
Hello,

I tried it but it doesn't work, anyway I have a different version of chrome (88).
any ideas? (I tried it on iphone and it works)

**Comment by opusonline** [comment]
Hi.
This error has nothing to do with eyeson, this is an error that shows that the browser can't access the video cam.
I'm pretty sure you will get the same results with other WebRTC tools.

https://test.webrtc.org/
https://webrtc.github.io/samples/src/content/devices/input-output/
https://webrtc.github.io/samples/src/content/getusermedia/gum/
https://app.eyeson.team/quicktest/
